### PR TITLE
An attempt to fix the UI tests

### PR DESCRIPTION
**Pull request by willdurand**
fixes https://github.com/mozilla/addons-frontend/issues/9980, maybe

### CODE REVIEW

**Comment by willdurand** [comment]
@jrbenny35 could you help me figure out a few things like: why are the expected add-ons named `Ui-Addon` in the test cases? It looks like we generate a lot of different add-ons so why these add-on names specifically?

Note: I fixed the addons-server command in https://github.com/mozilla/addons-server/commit/2fa4e2ff6d6438b81d3ed42799d9fe7d8b8c9ee9, so we do generate add-ons correctly but the expectations are not correct anymore.

**Comment by jrbenny35** [comment]
> @jrbenny35 could you help me figure out a few things like: why are the expected add-ons named `Ui-Addon` in the test cases? It looks like we generate a lot of different add-ons so why these add-on names specifically?
> 
> Note: I fixed the addons-server command in [mozilla/addons-server@2fa4e2f](https://github.com/mozilla/addons-server/commit/2fa4e2ff6d6438b81d3ed42799d9fe7d8b8c9ee9), so we do generate add-ons correctly but the expectations are not correct anymore.

We named them ```Ui-Addon``` so that we can look for them within tests. Some addons were generated using factories, and specific addons that we needed for testing had a ```Ui-Addon``` name added to them.

The current failures look unrelated to any specific changes but more to a config error within docker-compose maybe. https://app.circleci.com/pipelines/github/mozilla/addons-frontend/3494/workflows/e08f92a7-78f6-4dc8-abfe-70bd9fb906c0/jobs/25080

**Comment by willdurand** [comment]
> We named them `Ui-Addon` so that we can look for them within tests. Some addons were generated using factories, and specific addons that we needed for testing had a `Ui-Addon` name added to them.

@jrbenny35 it looks like the order of the search results was fixed (or expected to never change), right?

**Comment by willdurand** [comment]
@jrbenny35 meta-question: should we keep those ui tests in this repo given that there is a new repo with integration tests for/by QA? I'd keep the smoke tests in this repo but that integration test suite could be removed IMO (I was initially in favor of keeping it but it's hard to maintain).

**Comment by willdurand** [comment]
see https://github.com/mozilla/addons-frontend/pull/9985

**Pull request closed without merging**
