### PR TITLE
Fixed permission card border issue

### LINKED ISSUE #9588: Remove border radius between the main Permissions card and the Card-footer
Follow up for #9551

### Describe the problem and steps to reproduce it:
1. Open the following add-on detail page - https://addons-dev.allizom.org/en-US/firefox/addon/more-optional-permissions/
2. Scroll down to the Permissions card section
3. Observe the card styling 

### What happened?
There is a border radius between the main Permissions card and the Card-footer

### What did you expect to happen?
No border radius

### Anything else we should know?

[1] - Current layout on -dev:
image

[2] - Expected layout (seen on [stage](https://addons.allizom.org/en-US/firefox/addon/all-of-thepermissionsplurals/)):
image

### PR DESCRIPTION
**Pull request by lakshyabatman**
Fixes #9588

The border between the permission card content and expand link is fixed while making sure there is border-radius when the card is expanded.

Screenshot 2020-08-26 at 12 12 36 PM
Screenshot 2020-08-26 at 12 12 34 PM

### CODE REVIEW

**Review by eviljeff — CHANGES_REQUESTED** [review]
Can you remove the package-lock.json file from the PR? Looks fine otherwise.

**Comment by lakshyabatman** [comment]
@eviljeff , resolved changes.

**Comment by eviljeff** [comment]
The CI tests are failing.  Can you look at:
https://travis-ci.org/github/mozilla/addons-frontend/jobs/727354731#L242 and
https://travis-ci.org/github/mozilla/addons-frontend/jobs/727354730#L254 in particular.

**Comment by lakshyabatman** [comment]
@eviljeff , I've fixed the issue which was causing CI build to fail.

**Review by eviljeff — APPROVED** [review]
r+ thanks

**Comment by caitmuenster** [comment]
Thanks so much for the patch, @lakshyabatman! 🙌 Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition). 

Welcome onboard! We look forward to seeing you around the project.

**Pull request merged**
