### PR TITLE
Log page views for client-side navigation

### PR DESCRIPTION
**Pull request by willdurand**
Fixes https://github.com/mozilla/addons-frontend/issues/8647

---

I don't know if we need more but it seems to work locally for me so.. I
looked at various options and it looks like `history.listen()` is both
simple and functional.

### CODE REVIEW

**Comment by willdurand** [comment]
>     1. It includes a page title ([the `dt` param](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#title)), which refers to the previous page, not the current page. I don't know what, if anything, we're using that field for on GA, but it doesn't seem good that it sends the wrong title with the `pageview` hit. It looks like what's happening is that `dt` is defaulting to `document.title` (as documented at the link above) and I guess the beacon is being constructed/sent before the title of the new page is resolved. I'm not sure how we'll fix this, but I think we probably should.

Ugh, ok, that's something to fix.

>     2. The data describing the page being sent seems incorrect. There are three fields that can be used to identify a page, [`Document location URL`](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#location), via the `dl` param, [`Document Host Name`](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#hostname), via the `dh` param, and [`Document Path`](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#page), via the `dp` param.

Yeah, but that looks good to me. We use `dp`, which is a virtual path. I followed this guide: https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications, so I don't know what else we can do. I am not sure we should tune what GA sends, but maybe we should?

> Looking at the data sent in the beacon, I can see that `dl` is not being sent with the URL to the current page, but rather it is the URL when the site is initially loaded. That is, it never changes as you navigate from page to page.

Yep, and I read that we should not change it in: https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications#do_not_update_the_document_location, so I don't k now...

> `dp` is being sent with the proper path, but `dh` isn't sent at all. According to the [docs](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#page) "For 'pageview' hits, either &dl or both &dh and &dp have to be specified for the hit to be valid." So the beacon we are sending appears to be invalid, at least according to that (but maybe the docs are wrong?).

Ugh. Interesting, I don't know but I thought using the high-level GA tools seemed better to me. Did we ever check the existing GA calls?

For instance, the "install warning" beacons send a `dl` that is always the initial URL, not the URL of the actual extension.

This would get fixed by simply calling `setPage` on every location change.
 
> I'm also not sure that what we're doing for page views in `tracking.js` is the best way to go about it. I know this is old code, but, AFAICT, it's code that's never been used (or at least isn't currently in use). It doesn't make a lot of sense to me that we have to call both `tracking.setPage()` and then `tracking.pageView()` in order to send a `pageview` event to GA. If we always have to do both (and the way it's written we do), why not have a single function we can call? Going even further, it looks like we don't need to have the code in `tracking.js` call `ga('set', 'page', page)` at all (which is what `tracking.setPage` does). It looks like we could just call `ga('send', 'pageview', data)` and [set a value for `page` in `data`](https://developers.google.com/analytics/devguides/collection/analyticsjs/tracker-object-reference#parameters_2). I suppose calling `ga('set', 'page', page)` could be useful if we are going to be sending other data from the same page (such as an event), and we want to be able to track from which page an event was sent, so maybe we should keep both calls, but I still think it makes sense to wrap them in a single function in `tracking.js`.

According to the docs, these are 2 different things so I'd rather keep things as is.

**Comment by willdurand** [comment]
> > ```
> > 1. It includes a page title ([the `dt` param](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#title)), which refers to the previous page, not the current page. I don't know what, if anything, we're using that field for on GA, but it doesn't seem good that it sends the wrong title with the `pageview` hit. It looks like what's happening is that `dt` is defaulting to `document.title` (as documented at the link above) and I guess the beacon is being constructed/sent before the title of the new page is resolved. I'm not sure how we'll fix this, but I think we probably should.
> > ```
> 
> 
> Ugh, ok, that's something to fix.

I see what the problem is. We listen to the location change but it does not mean the component page has full loaded (i.e. replaced the HTML title). Ha. Ha. That does not sound fun.

**Comment by kumar303** [comment]
Maybe [`MutationObserver`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) could help?

**Comment by muffinresearch** [comment]
@willdurand would it be possible to see about moving forward with this around other things going on? I think it's fine even if the title part isn't perfect. That would at least help us to see traffic flowing around the site.

**Comment by willdurand** [comment]
> @willdurand would it be possible to see about moving forward with this around other things going on? I think it's fine even if the title part isn't perfect. That would at least help us to see traffic flowing around the site.

Yep.

**Comment by willdurand** [comment]
So the page title issue is likely caused by react-helmet: https://github.com/nfl/react-helmet/issues/189

**Comment by willdurand** [comment]
> > > ```
> > > 1. It includes a page title ([the `dt` param](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#title)), which refers to the previous page, not the current page. I don't know what, if anything, we're using that field for on GA, but it doesn't seem good that it sends the wrong title with the `pageview` hit. It looks like what's happening is that `dt` is defaulting to `document.title` (as documented at the link above) and I guess the beacon is being constructed/sent before the title of the new page is resolved. I'm not sure how we'll fix this, but I think we probably should.
> > > ```
> > 
> > 
> > Ugh, ok, that's something to fix.
> 
> 
> I see what the problem is. We listen to the location change but it does not mean the component page has full loaded (i.e. replaced the HTML title). Ha. Ha. That does not sound fun.
> 
> It likely means that we need a way to know when a page is fully loaded, can we do that? 😐

It is not trivial to fix that because when we are navigating to a new page, we do not have any data yet (usually), so we render once the page with the generic title and fetch the data, then we receive the data and re-render the page with the data.

I tried to defer the GA calls, but we would need to defer these calls twice (or more), i.e. until we have the page with the final data. I don't know how to do that programmatically.

The alternative approach that works is to defer the GA calls for 1 second, because all our pages load in less that 1 second anyway. I could confirm that accurate data is sent to GA, but that's more of an empirical approach.

Reading [this](https://github.com/nfl/react-helmet/issues/189), the Google autotrack plugin is also affected and there is no easy fix.

**Comment by willdurand** [comment]
> Maybe [`MutationObserver`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) could help?

I wanted to try listening to `title` change instead, and `MutationObserver` does help indeed. The problem is that we will track **most** page views but not all of them...

I believe we will not track some of the search page views because the title does not always change (e.g., when changing the OS). That being said, I am not sure that a different solution would track such changes either (when only query params change).

@muffinresearch what do you think?

The `MutationObserver` is very accurate and arguably simpler, I think.

**Comment by muffinresearch** [comment]
> > Maybe [`MutationObserver`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) could help?
> 
> I wanted to try listening to `title` change instead, and `MutationObserver` does help indeed. The problem is that we will track **most** page views but not all of them...
> 
> I believe we will not track some of the search page views because the title does not always change (e.g., when changing the OS). That being said, I am not sure that a different solution would track such changes either (when only query params change).
> 
> @muffinresearch what do you think?
> 
> The `MutationObserver` is very accurate and arguably simpler, I think.

I think this sounds ok to me. We should try it out and see what the data ends-up looking like.

**Comment by willdurand** [comment]
mmm that does not work as I expected, when we navigate to a new add-on that has never been seen before, we send 2 pageviews to GA (before it is loaded and once it is loaded).

**Comment by willdurand** [comment]
I can think of two generic implementations for sending page views to GA:

1. If we listen to `LOCATION_CHANGE` (or use `history.listen()`) then we end up in @bobsilverberg's first comment:

> It includes a page title (the dt param), which refers to the previous page, not the current page. I don't know what, if anything, we're using that field for on GA, but it doesn't seem good that it sends the wrong title with the pageview hit. It looks like what's happening is that dt is defaulting to document.title (as documented at the link above) and I guess the beacon is being constructed/sent before the title of the new page is resolved. I'm not sure how we'll fix this, but I think we probably should.

2. If we use `MutationObserver`, we will likely send more events that needed (because it takes 2 title changes to fully load a new page) 😕 

We decided to use the simplest solution anyway during today's standup meeting (option 1), even if the title is not accurate. As stated above, we'll send the previous title for all client-side page views.

It has been suggested to change the title value sent to GA. This seems feasible according to https://developers.google.com/analytics/devguides/collection /analyticsjs/pages#pageview_fields. This makes sense because no title is probably better than an invalid one.

Should we implement option 1 and see if we can omit or empty the title then?

/cc @bobsilverberg @muffinresearch

**Comment by bobsilverberg** [comment]
> 
> Should we implement option 1 and see if we can omit or empty the title then?
> 

I am in favour of doing this.

**Comment by willdurand** [comment]
@bobsilverberg I updated the patch and it seems to work. Locally, I disabled the `beacon` transport to better see the parameters sent to GA. It would be great if you could take a look when you have time, thanks!

**Comment by willdurand** [comment]
> This looks good, thanks @willdurand. I did look at the data that is being sent by the beacon, and I still see that `dl` remains whatever page was initially loaded for the site, even though we are calling `setPage` on every location change, so I'm not sure if that's something we need to address or not. Maybe `dl` is for "landing page" (even though that doesn't match the docs), and in that case it is correct?

Quote from [this page](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#dl):

> Use this parameter to send the full URL (document location) of the page on which content resides. You can use the &dh and &dp parameters to override the hostname and path + query portions of the document location, accordingly. The JavaScript clients determine this parameter using the concatenation of the document.location.origin + document.location.pathname + document.location.search browser parameters. Be sure to remove any user authentication or other private information from the URL if present. For 'pageview' hits, either &dl or both &dh and &dp have to be specified for the hit to be valid.

I believe that would work then, but as you said, let's try it for real in -dev.

**Pull request merged**
