### PR TITLE
Default the expiry date for cookies created by withExperiment to 30 days

### LINKED ISSUE #8515: withExperiment should set a permanent cookie
Currently, the cookie set by [`withExperiment`](https://github.com/mozilla/addons-frontend/blob/master/src/core/withExperiment.js#L80) is a [`session` cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Session_cookies), which means that it is (generally) cleared when the browser closes.

For the purposes of keeping a user's experience consistent, and also being able to assume that the behaviour for a user over time is based on a consistent experience, it seems that we should be setting a [`permanent` cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Permanent_cookies) instead. We probably shouldn't create a cookie that never expires, but ideally the cookie would remain for the duration of the experiment. Perhaps a default of 1 month would be good, but perhaps we should allow this to be overridden by the experiment in question (via the call to `withExperiment`).

@willdurand / @kumar303 / @felixlawrence what are your thoughts?

For QA:

Please confirm that the cookie that is set (you can use the `installButtonWarningExperiment` cookie) has an expiry date that is 30 days (2592000 seconds) in the future.

Note that this patch should also address the issue reported about the A/B test using session cookies as discussed at https://github.com/mozilla/addons-frontend/issues/8137#issuecomment-525801292.

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #8515 

This makes the default expiry date of a cookie created via `withExperiment` 30 days in the future (2592000 seconds, to be exact). This can be overridden for a particular experiment by passing a `cookieConfig` property into the call to `withExperiment`, which can then specify a different expiry date.

### CODE REVIEW

**Comment by bobsilverberg** [comment]
> Shouldn't this be covered by a test case?
> 
> Otherwise r+

I did update the test case to verify that the code that sets the cookie passes the `defaultCookieConfig` to the call to `cookie.set`. That seems like all the coverage we'd want. If we go further and check to see that the cookie was actually set with the expected expiry date, then we'd be testing the package rather than our code.

Do you disagree?

**Comment by willdurand** [comment]
I think if we change the default expiration date by mistake, the test case will still pass and maybe that's not what we want.

**Comment by bobsilverberg** [comment]
> I think if we change the default expiration date by mistake, the test case will still pass and maybe that's not what we want.

That's true, but I also feel like there has been lots of conversation in the past about "not testing configuration", and that's exactly what you're suggesting doing. I suppose if we really wanted to be careful about this not being able to change by accident I could create a function that returns the default maxAge, and then add a test for that function, verifying that it returns 30 days in seconds. Does that sound like a reasonable thing to do, and would that address your concern?

**Comment by willdurand** [comment]
Maybe add a comment saying that the value should not be changed and link to the original issue so that we know why.

**Pull request merged**
