### PR TITLE
Fix Dropdown mouse click

### LINKED ISSUE #8424: “More…” drop down menu doesn't close on first mouse click
### STR:
1. Access AMO homepage: https://addons.allizom.org/en-US/firefox/.
2. Mouse hover the “More…” menu button from the page header.
3. Click on the More button.

### Expected result:
Drop down menu should disappear after the mouse click.

### Actual result:
The drop down menu is open.

### Notes:
Same thing happens for the User profile drop down menu, located at the top right side from the page header, after logging in.
Reproduced in amo-dev, amo-stage and amo-prod with Fx68, Win10x64.

2019-07-16_14h50_17

### PR DESCRIPTION
**Pull request by TheSTL**
Fixes #8424 

Replace this sentence with a description of how your patch fixes the issue.

The handleClick function is checking if the element is in hover state or not. If it's in hover state and clicked then it set hover state to be `false` and return. Then we again clicked then it then it's checking that state is `false` then drop down state change and hide. That's the reason every time the mouse enters the element and has to clicked twice to close the dropdown.

```
 if (this.state.setByHover) {
      this.setState({ setByHover: false });
      return;
    }
```

Just by removing this if condition dropdown works as expected.

### CODE REVIEW

**Comment by bobsilverberg** [comment]
Thanks for the patch @TheSTL, nice work! It seems to work well, but I'm just trying to get set up to test it on Android. I will merge it once I'm sure it doesn't break anything on Android.

**Comment by TheSTL** [comment]
Thanks @bobsilverberg

**Comment by bobsilverberg** [comment]
@willdurand I have been unable to connect my Android device and get USB debugging working. Is this something you're able to do to give a quick test for this patch? If not, I am inclined to merge it and test it on dev.

**Comment by willdurand** [comment]
> @willdurand I have been unable to connect my Android device and get USB debugging working. Is this something you're able to do to give a quick test for this patch? If not, I am inclined to merge it and test it on dev.

Okay, I'll take a look. Let's chat to see why you're not anble to use the FF debugger today, that's very useful.

**Comment by TheSTL** [comment]
Thanks @bobsilverberg

**Comment by caitmuenster** [comment]
Thanks @TheSTL! :) Your contribution has been added to our [contribution wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition). 

Would you be interested in creating a profile on mozillians.org? I'd be happy to vouch for you!

**Comment by TheSTL** [comment]
Hi @caitmuenster there is my  profile - [thestl](https://mozillians.org/en-US/u/thestl/)

**Comment by caitmuenster** [comment]
Thanks @TheSTL! Your profile is vouched. ✨

Welcome onboard! I look forward to seeing you around the project.

**Comment by TheSTL** [comment]
Thanks @caitmuenster :)

**Pull request merged**
