### PR TITLE
Fix: Sections titles are not RTL #2605

### LINKED ISSUE #2605: Sections titles are not RTL
Steps to reproduce:
1. Load Details page for any extension on device i.e. https://addons-dev.allizom.org/en-US/android/addon/home-links/?src=hp-dl-featured
2. Change the language to a RTL one https://addons-dev.allizom.org/ar/android/addon/home-links/?src=hp-dl-featured
3. Observe sections titles

Expected results:
Titles are RTL.

Actual results:
Title are not RTL.

Notes/Issues:
- issue is also reproducing on new desktop pages
- issue is reproduced while in Extenions/Themes homepages

Verified on AMO-dev FF53(Android 7.1.2, Win 7).
Screenshots for this issue:

### PR DESCRIPTION
**Pull request by tsl143**
Fixes #2605

### CODE REVIEW

**Comment by tofumatt** [comment]
Can you please provide screenshots for what these look like?

I'm a bit surprised, I thought `text-align: left` would put things on the right side for RTL. Oops!

**Comment by tsl143** [comment]
Even surprising for me `text-align: left` doesnt work as expected with `[dir=rtl]`. Also `text-align: left` was doing no good to `Cards-Header`
Screen shots (sorry my bad, I took them before but forgot to upload :( )

**before**
screen shot 2017-06-20 at 1 09 02 pm

**After**
screen shot 2017-06-20 at 12 53 54 pm

**Comment by tsl143** [comment]
ping @tofumatt

**Comment by tofumatt** [comment]
Sorry about this but during a redesign this got fixed indecently. Thanks for working on this and sorry I didn't get to review it before I merged my own patch 😞

**Comment by tsl143** [comment]
NP :)

**Pull request closed without merging**
