### PR TITLE
chore(package): update jest to version 21.0.1

### PR DESCRIPTION
**Pull request by kumar303**
Closes #3067

### CODE REVIEW

**Comment by kumar303** [comment]
Hmm. This may be related https://github.com/facebook/jest/issues/1852

**Comment by willdurand** [comment]
Or this: https://github.com/facebook/jest/issues/3251#issuecomment-327814839

**Comment by willdurand** [comment]
Superseded by #3088

**Comment by muratkorkmaz106** [comment]
Afiyet all

**Pull request closed without merging**
