### PR TITLE
Check bundle size in CI against a threshold

### PR DESCRIPTION
**Pull request by kumar303**
Fixes https://github.com/mozilla/addons-frontend/issues/2691

### CODE REVIEW

**Comment by kumar303** [comment]
@muffinresearch I was mistaken. This patch doesn't require GitHub access because all it does is fail if we dip below our own hard-coded threshold. 

It doesn't give us graphs over time or anything fancy. Obviously when we hit the max we'll have to bump the threshold but at least that will force us to consider the impact of such a change.

**Comment by kumar303** [comment]
The output is kind of terrible since our build log is too big for Travis. Here's where it shows the bundle sizes in the raw log:

screenshot 2017-08-09 12 17 54

And now my memory has been jogged. They do offer [TravisCI integration](https://github.com/siddharthkp/bundlesize#2-build-status) which is where I got rejected when requesting access for it. I'm not sure what "cool features" it provides so it would probably be worth landing the patch without it.

**Comment by muffinresearch** [comment]
I wonder if we should make the test output quiet for travis (with --silent IIRC) on the basis that individual failures should still be visible - I found the amount of noise got in the way recently too when looking for what had failed.

**Comment by kumar303** [comment]
> Might be nice to ... track locale bundles

I was looking into this at first but for some reason locale files aren't getting built with this command. I couldn't figure out why and I don't want to spend too much time on it. Maybe you have some ideas? I filed it here: https://github.com/mozilla/addons-frontend/issues/2923

**Comment by kumar303** [comment]
> I wonder if we should make the test output quiet for travis?

Hmm, I don't see a way to do this easily. Maybe we can fix it up later.

Thanks for the review!

**Pull request merged**
