### PR TITLE
[fix]: Added cursor pointer style to dropdown

### LINKED ISSUE #9301: [ui] Cursor should be changed on hover on the dropdowns
### Describe the problem and steps to reproduce it:

Dropdown in the reviews page should change cursor from `normal` to `pointer` so that user can understands that it is selectable.
Also, dropdown in the addon page of `Add to collection` card, also shows the same behaviour.

Here is the screenshot:

Screenshot from 2020-03-29 11-42-59

Screenshot from 2020-03-29 17-07-28

### Solution:
We can change the cursor on hover by adding style `cursor: pointer;`.

Here is the screenshot:

Screenshot from 2020-03-29 11-49-03

Screenshot from 2020-03-29 17-08-31

I would like to work on this issue :+1:

### PR DESCRIPTION
**Pull request by muskangupta-iitr**
Fixes #9301 

Added style for changing cursor from `normal` to `pointer` on hover to dropdown for making it look selectable.

#### Before:

Screenshot from 2020-03-29 11-42-59

Screenshot from 2020-03-29 17-07-28

#### After:

Screenshot from 2020-03-29 11-49-03

Screenshot from 2020-03-29 17-08-31

### CODE REVIEW

**Comment by muskangupta-iitr** [comment]
@willdurand @muffinresearch Please review!

**Comment by bobsilverberg** [comment]
> @willdurand @bobsilverberg @muffinresearch Please review!

@muskangupta-iitr Just a small piece of advice, when asking someone to review your code, you might want to say something like "could you please review my patch" as opposed to "Please review!", which comes across as a bit less polite.

**Comment by muskangupta-iitr** [comment]
> > @willdurand @bobsilverberg @muffinresearch Please review!
> 
> @muskangupta-iitr Just a small piece of advice, when asking someone to review your code, you might want to say something like "could you please review my patch" as opposed to "Please review!", which comes across as a bit less polite.

I am so sorry for that. I will be extra careful from next time.

**Comment by muskangupta-iitr** [comment]
@bobsilverberg I am really really sorry for this. I never meant to disrespect any of you, I respect all of you very much for you really great guidance. I am just a little new to this world and I assure you I would make sure such mistakes are not repeated in future. Really, really sorry for hurting and offending. Please accept my apologies, would never happen in future. And also, a real thanks for pointing out my mistake. 
Sorry! :(

**Comment by muskangupta-iitr** [comment]
> This looks good and seems to work. Thanks for the patch @muskangupta-iitr.
> 
> Just a note, though, you do already have two other PRs currently being reviewed and we think it best if you not work on more than two at a time. Not only will that allow you to focus on the more complex patches, but also will not overload us with reviews for so many patches.

Yes @bobsilverberg! I just noticed this bug while going through the website. Just can't stop myself from contributing :sweat_smile:. I will be only focusing on those PR's. Thanks :+1:

**Comment by bobsilverberg** [comment]
> @bobsilverberg I am really, really sorry for this. I never meant to disrespect any of you, I respect all of you very much for your really great guidance. I am just a little new to this world and I assure you I would make sure such mistakes are not repeated again in future. Really, really sorry for hurting and offending. Please accept my apologies, would never happen in future. And also, a real thanks for pointing out my mistake.
> Sorry! :(

It's okay. I don't think anyone was offended by it - I just wanted to point it out to you so you'll keep it in mind in the future. It's a good think to think about when interacting with any open source project. Thanks for listening and acknowledging it.

**Pull request merged**
