### PR TITLE
Hack around bug in PhotoSwipe

### LINKED ISSUE #1712: Screenshots preview is not working for second add-on
Steps to reproduce:
1. Open AMO-dev on your Android device
2. Load details page for an add-on
3. Navigate through screenshots in full mode preview
4. Go to another add-on details and try to navigate to its screenshots in full mode preview

Expected results:
User can navigate through screenshots in full mode preview with not problems.

Actual results:
Screenshots section turns into with for the second add-on. Screenshot cannot longer be previewed.

Notes/Issues:
Verified on AMO-dev FF51(Android 6.0.1).
Video for this issue: 
noscrrn

### PR DESCRIPTION
**Pull request by muffinresearch**
Fixes #1712 

Original function is here: https://github.com/minhtranite/react-photoswipe/blob/05602e52755cc69d1f530a64a65cc5b6b0b225b9/src/PhotoSwipeGallery.js#L36

This is a bit of a hack but it overloads the function used to get thumbnails so that the second time photoswipe is loaded it continues to work.

This will need coverage (or skips to coverage) but if you have a moment it would be spin this up in review and check it solves the problem.

### CODE REVIEW

**Comment by Ryuno-Ki** [comment]
Have  you filled a ticket against upstream?

**Comment by muffinresearch** [comment]
> Have you filled a ticket against upstream?

No, because one already exists.

**Comment by Ryuno-Ki** [comment]
Could you link it here, so others could take a look for when it gets resolved, too?

Or better, open a ticket that the workaround gets removed once the fix lands upstream.

**Comment by tofumatt** [comment]
Note as well: that repo is quite old and seemingly unmaintained, given some open pull requests from last year with no author/maintainer comments.

Long term we'll likely want to fork it or something. But this is good for next week 😄

**Pull request merged**
