### PR TITLE
add dicts to user profile

### LINKED ISSUE #9469: Dictionary extensions missing from developer profile pages
[Dictionary extensions](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/dictionaries) (used by the Firefox spellchecker) are not displaying on developer profile pages, even though they are counted under "Number of add-ons".

Example:

- https://addons.mozilla.org/en-US/firefox/user/142774/
  - https://addons.mozilla.org/en-US/firefox/addon/romanian-spellchecking-diction/

-----

By the way, [this extension](https://addons.mozilla.org/en-US/firefox/addon/romanian-spellchecking-diction/) ought to be included in the [language tools page](https://addons.mozilla.org/en-US/firefox/language-tools/).

### PR DESCRIPTION
**Pull request by Yrkan**
Fixes #9469 

Now the directories are showing, but I'm not sure how do we want to show it, currently it is similar to themes.

### CODE REVIEW

**Comment by Yrkan** [comment]
**Also, does this need an associated test ?**

**Comment by bobsilverberg** [comment]
@willdurand I assigned the review to you as you are listed as the mentor for #9469. 

@Yrkan At first glance it looks like this is not the solution we want to implement, as I believe the idea was to list the dictionaries along with the extensions, not as a separate card.

**Comment by Yrkan** [comment]
@bobsilverberg  yeah my bad, I'll update the PR with the right implementation

**Comment by Yrkan** [comment]
I wonder how we want to approach this currently I'm thinking about changing addonType to an array, and use join(",") to join ADDON_TYPE_EXTENSION and ADDON_TYPE_DICT.
@willdurand what do you think ?

**Comment by willdurand** [comment]
> I wonder how we want to approach this currently I'm thinking about changing addonType to an array, and use join(",") to join ADDON_TYPE_EXTENSION and ADDON_TYPE_DICT.

Well, yes. That sounds like a good idea but it's going to require a lot of changes.

Maybe one thing we could do is replace `addonType=ADDON_TYPE_EXTENSION` with `addonType=ADDON_TYPE_EXTENSION,ADDON_TYPE_DICT` in the [saga](https://github.com/mozilla/addons-frontend/blob/6ebb82b440b7638bd622096a54d530813d5a6ca8/src/amo/sagas/addonsByAuthors.js#L39). That would be correct since Jorge said that we'd want to "group dictionaries with extensions". We're using this `addonsByAuthors` code in two places: user profiles and add-on detail pages. I think replacing the `addonType` in the saga would be ok but I'd like to know what @bobsilverberg thinks first.

**Comment by bobsilverberg** [comment]
> > I wonder how we want to approach this currently I'm thinking about changing addonType to an array, and use join(",") to join ADDON_TYPE_EXTENSION and ADDON_TYPE_DICT.
> 
> Well, yes. That sounds like a good idea but it's going to require a lot of changes.
> 
> Maybe one thing we could do is replace `addonType=ADDON_TYPE_EXTENSION` with `addonType=ADDON_TYPE_EXTENSION,ADDON_TYPE_DICT` in the [saga](https://github.com/mozilla/addons-frontend/blob/6ebb82b440b7638bd622096a54d530813d5a6ca8/src/amo/sagas/addonsByAuthors.js#L39). That would be correct since Jorge said that we'd want to "group dictionaries with extensions". We're using this `addonsByAuthors` code in two places: user profiles and add-on detail pages. I think replacing the `addonType` in the saga would be ok but I'd like to know what @bobsilverberg thinks first.

That sounds like a reasonable solution to me. We'll end up with the dictionaries and extensions mixed together, but it sounds like that would be fine. Can you confirm that @jvillalobos?

**Comment by jvillalobos** [comment]
Sounds fine to me.

**Comment by willdurand** [comment]
I am going to close this PR for now. Feel free to reopen if you want to continue the work in progress there.

**Pull request closed without merging**
