### PR TITLE
Fixing style add to FF button on small screens on versions page

### LINKED ISSUE #7346: The install button should use the full width below the text of each version on the version page (on small screens)
The install button should be displayed below the text of each version on the version page (on small screens) and use the full width, rather than staying next to the content. This would match the style of the install button on an add-on detail page.

### Current:

screen shot 2019-01-09 at 11 16 01

### Expected:

screen shot 2019-01-09 at 11 22 38

### PR DESCRIPTION
**Pull request by championshuttler**
Fixes #7346

cc @bobsilverberg 

After:

image

### CODE REVIEW

**Comment by championshuttler** [comment]
@bobsilverberg I am not sure about this method , I was trying to use flex but IDK what's the reason it was not working for me I was trying something like: 
```
  .InstallButtonWrapper {
    @include respond-to(medium) {
      direction: flex;
      flex-direction: column;
      align-self: flex-end;
  }
```

If we need to approach in this way can you help where i am getting wrong and correct me please. 
Thanks

**Comment by bobsilverberg** [comment]
Thanks for this @championshuttler. I actually just put up a PR that addresses a number of visual issues for the page, and it partially addresses what you've done here, but not the 100% width part. Can I suggest that you wait for https://github.com/mozilla/addons-frontend/pull/7370 to be merged and then rebase your patch on top of that?

**Comment by bobsilverberg** [comment]
@championshuttler PR #7370 has landed, so it's safe to rebase this patch against the latest master and then see what's left to do.

Thanks!

**Comment by championshuttler** [comment]
Oops just did some blunder with `git` , opening a new PR in a while sorry for noise :/

**Comment by championshuttler** [comment]
New PR Link -> https://github.com/mozilla/addons-frontend/pull/7392

**Pull request closed without merging**
