### PR TITLE
Register/Log in" button made solid

### LINKED ISSUE #3705: "Register/Log in" button needs to be made solid
We don't have a ghost/outline button spec yet in the design system, so until then, we need to make this button solid. I'll provide the proper spec for this soon.
screen shot 2017-10-30 at 7 42 34 pm

### PR DESCRIPTION
**Pull request by anweshknayak**
fixes #3705 
Register/Log in" button made solid by following https://design.firefox.com/photon/components/buttons.html

* [x] This PR relates to an existing open issue and there are no existing
      PRs open for the same issue.
* [x] Add `Fixes #ISSUENUM` at the top of your PR.
* [x] Add a description of the the changes introduced in this PR.
* [x] The change has been successfully run locally.
* [ ] Add before and after screenshots (Only for changes that impact the UI).

### CODE REVIEW

**Comment by anweshknayak** [comment]
@kumar303 @tofumatt @muffinresearch can anyone review?

**Comment by tofumatt** [comment]
Hi @anweshknayak, thanks for filing. I didn't notice this issue before but I'm actually working on it in a more involved button refactor. The new patch takes a slightly different approach so I'm going to close this but I'll assign that other issue to myself so there isn't confusion.

Sorry about that!

**Comment by kumar303** [comment]
@anweshknayak thanks a lot for taking the time to work on this. The most helpful thing would be try and grab a [good first bug](https://github.com/mozilla/addons-frontend/issues?q=is%3Aissue+is%3Aopen+label%3A%22contrib%3A+good+first+bug%22) issue since those are less likely to have someone working on them. However, we typically do assign an issue before working on them so if you want to work on any other unassigned issue it should be fine!

**Comment by anweshknayak** [comment]
thanks @kumar303 will stick to it :+1:

**Pull request closed without merging**
