### PR TITLE
Directory restructure

### PR DESCRIPTION
**Pull request by mstriemer**
Updated the directory structure. It should be pulling the app name from an environment variable or something.

I created this branch on mozilla/addons-frontend so anyone can push changes if needed. Hoping to make some more changes later tonight.

### CODE REVIEW

**Comment by mstriemer** [comment]
There are server files in `src/disco` and `src/search` now. They just inject the routes into the base server from `src/core/server.js`. The files are the same, it's just that the relative paths are different for loading routes.

This might not actually be ideal for development. We may want to run it all together just out of convenience. It could get annoying to need to restart the server to work on the editor tools then the regular frontend.

I added two tasks: `npm run dev:disco` and `npm run dev:search`.

Folder structure is:

```
- src/
  - core/
    - components/
    - server.js
  - disco/
    - components/
    - client.js
    - server.js
    - routes.js
  - search/
    - components/
    - client.js
    - server.js
    - routes.js
- test/
  - core/
    - components/
  - disco/
    - components/
  - search/
    - components/

**Comment by tofumatt** [comment]
Yeah, the option to run all the servers together makes sense to me, at least for development.

**Comment by mstriemer** [comment]
I added a server file to `core` that loads both sets of routes. That's probably the best call for development. We still need to figure out the webpack thing for multiple bundles for these apps to load.

**Comment by muffinresearch** [comment]
Looks good to me. I think it'll make sense to land this and then you can iterate on it further with more branches.

**Pull request merged**
