### PR TITLE
[fix]: Fixed console warning by adding keys to the items

### LINKED ISSUE #9255: [warning] Console warning for adding key in the SiteNoticesBase
### Describe the problem and steps to reproduce it:
There is warning coming in logs for adding a unique key to the list items in SiteNoticesBase component.
Here is the Screenshot:

Screenshot from 2020-03-22 20-42-35

I would like to solve this issue!

### PR DESCRIPTION
**Pull request by muskangupta-iitr**
Fixes #9255 

Fixed the console warning of adding keys to the list items by adding unique keys to the items.

### CODE REVIEW

**Comment by muskangupta-iitr** [comment]
@willdurand Please review!

**Comment by willdurand** [comment]
Thanks @muskangupta-iitr!

**Comment by caitmuenster** [comment]
Woohoo, thanks for the patch @muskangupta-iitr! 🎉 Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition). 

Would you be interested in creating an account on mozillians.org? I'd be happy to vouch for you!

**Comment by muskangupta-iitr** [comment]
Thanks, @caitmuenster for the appreciation. It really means a lot to me. I would love to create an account, in fact, it would be an honor for me. I am really glad you liked my work, would love to make more such contributions under your team’s guidance and support and learn from the experiences. 
Thanks a lot :)
Really, really glad :D

**Comment by muskangupta-iitr** [comment]
> Woohoo, thanks for the patch @muskangupta-iitr! 🎉 Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition).
> 
> Would you be interested in creating an account on mozillians.org? I'd be happy to vouch for you!

https://mozillians.org/en-US/u/muskangupta_iitr/ 
Here's the link to my Mozilla account, I would be really glad and thankful of you to vouch for me.
Thanks :)

**Comment by caitmuenster** [comment]
@muskangupta-iitr Yay! You're vouched. ✨ Welcome onboard -- we look forward to seeing you around!

**Comment by muskangupta-iitr** [comment]
@caitmuenster Thanks a lot :)

**Pull request merged**
