### PR TITLE
Support read-only star ratings

### PR DESCRIPTION
**Pull request by kumar303**
Fixes https://github.com/mozilla/addons-frontend/issues/1529

### CODE REVIEW

**Comment by kumar303** [comment]
@mstriemer good call on splitting it into two components! This will make the read-only usage a lot more concise. Since this was a a big change could you review it again after the holidays?

**Comment by kumar303** [comment]
Huh, weird, coverage said it fell but all the files in the report are at 100%

**Comment by kumar303** [comment]
Whoa, this patch almost got lost in Christmas pudding. I double checked that upstream changes didn't mess with the refactor.

**Comment by kumar303** [comment]
@mstriemer Oh, hehe, I asked you to review it again (I just read that). Well, the code works at least. Your call.

**Comment by mstriemer** [comment]
Oops, I'm going to have to run shortly but I'll take a look tonight or tomorrow.

**Comment by kumar303** [comment]
cleanup is happening in https://github.com/mozilla/addons-frontend/pull/1590

**Pull request merged**
