### PR TITLE
Fix how errors are passed to middleware (fixes Sentry)

### PR DESCRIPTION
**Pull request by kumar303**
Fixes https://github.com/mozilla/addons-frontend/issues/1942

### CODE REVIEW

**Comment by kumar303** [comment]
@tofumatt @muffinresearch it would be great to get some eyes on this as it doesn't have good test coverage. If you can test out the branch locally, that would be helpful too. I will make sure we have a bug on file to add proper tests but it will take some re-architecting so I didn't want to block on it.

**Comment by kumar303** [comment]
The existing tests definitely caught some issues. Mainly I was using a Sentry test instance to make sure the different errors were getting passed to the Raven middleware.

**Comment by muffinresearch** [comment]
I ran this locally and didn't see anything untoward as yet - probably be best to get this on -dev and see if more eyes on it there helps expose any issues.

**Comment by kumar303** [comment]
I filed https://github.com/mozilla/addons-frontend/issues/1961 to add proper tests. The existing functional tests do exercise quite a bit though and it caught a few mistakes I made. I agree about getting this on dev, let's do it! Thanks for the r.

**Pull request merged**
