### PR TITLE
fix : height fix for search box and register btn

### PR DESCRIPTION
**Pull request by tsl143**
Fix: #3186 

**Before:**
screen shot 2017-09-20 at 6 13 11 pm

**After:**
screen shot 2017-09-20 at 6 12 41 pm

### CODE REVIEW

**Comment by tofumatt** [comment]
Frustratingly now it's misaligned by being one pixel too high. It would be nice if there were a `1px` margin on both top and bottom.

What's the padding like on the search box? Maybe it's best to knock it down `1px`.

**Comment by muffinresearch** [comment]
Looks to me like the register button could easy handle some more of bottom padding and less top padding. The text looks off-centre though that might be partly an optical illusion.  

Might be possible to add the missing 1px that way too. It would be nice to get the text baselines of the input placeholder and the register button text more closely aligned.

**Comment by tofumatt** [comment]
That button style is from the spec, though. Changing just the one button is frustrating because then it doesn’t follow the spec. Adding the padding will change things elsewhere.

**Comment by muffinresearch** [comment]
> That button style is from the spec, though. Changing just the one button is frustrating because then it doesn’t follow the spec. Adding the padding will change things elsewhere.

Yep, that's a good point.

**Comment by tsl143** [comment]
@muffinresearch, Again nsp-check fails after master merge, 
But the fix @tofumatt suggested works
screen shot 2017-09-21 at 2 50 15 pm

**Comment by muffinresearch** [comment]
Thanks @tsl143

**Pull request merged**
