### PR TITLE
yarn 🏃 npm

### PR DESCRIPTION
**Pull request by mstriemer**
Add a yarn.lock file. We should be able to use yarn and npm together and see if it works for us. Delete the file if we don't want to switch.

yarn installs seem to be quicker than with npm, especially in the "nothing changed" case (0.19s vs 12.55s on my machine). This is pretty nice.

If you use yarn you can install with `yarn` and this file will get updated. If you don't use yarn then this file won't get updated until someone runs `yarn` and commits the results. Should work fine to see if people like it.

### CODE REVIEW

**Comment by mstriemer** [comment]
So I think that when the discopane UI tests landed Circle started running `tox` instead of `npm test` and that's why the tests started to fail. Since the UI tests are running on Travis and we aren't really using Circle anyway I just forced it to run `npm run test` instead. If we go through with setting up Circle we can fix it and add parallelism.

**Comment by muffinresearch** [comment]
Circle is being setup further by ops. See also https://github.com/mozilla/addons-frontend/pull/1202

**Comment by mstriemer** [comment]
@muffinresearch should I leave those changes out for now and merge the `yarn.lock` file?

**Comment by muffinresearch** [comment]
> @muffinresearch should I leave those changes out for now and merge the yarn.lock file?

Yeah I think it makes sense to leave out any changes to circle in this patch.

**Comment by mstriemer** [comment]
I removed the [commit](https://github.com/mstriemer/addons-frontend/commit/9839a9538595a63b76e73b846f28581501bd9c87) that updated circle. Just the yarn.lock file now.

**Pull request merged**
