### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Aanandgupta**
Codeofconduct redirects to 404 page
#10052 
fixing above issue

Fixes #ISSUE_NUMBER

Replace this sentence with a description of how your patch fixes the issue.

### CODE REVIEW

**Comment by willdurand** [comment]
Hey, could you link to `https://github.com/mozilla/addons-frontend/blob/master/.github/CODE_OF_CONDUCT.md` instead? thanks!

**Comment by Aanandgupta** [comment]
> 
> 
> Hey, could you link to `https://github.com/mozilla/addons-frontend/blob/master/.github/CODE_OF_CONDUCT.md` instead? thanks!

Yes Sure

**Comment by Aanandgupta** [comment]
> 
> 
> Hey, could you link to `https://github.com/mozilla/addons-frontend/blob/master/.github/CODE_OF_CONDUCT.md` instead? thanks!

Done the same Thanks

**Review by willdurand — APPROVED** [review]

**Comment by caitmuenster** [comment]
Thanks so much for the patch, @Aanandgupta! Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition). 🎉

Hope to continue seeing you around the project!

**Pull request merged**
