### PR TITLE
Redirect /android?something to /android/?something

### LINKED ISSUE #8059: Broken Link
### Describe the problem
I just installed firefox. I opened a new tab and moved to the bookmarks selection. I tapped the Firefox: customize with addons and it took me to a page that does not exist. This seems to be on the default home page.

### What happened?
The page it directed me to seemed to be where maybe a soecific add-on had been. I dont know where it was supposed to take me.
### Anything else we should know?

https://addons.mozilla.org/android?utm_source=inproduct&utm_medium=default-bookmarks&utm_campaign=mobileandroid

### PR DESCRIPTION
**Pull request by willdurand**
Fixes #8059

---

This fixes #8059 by introducing a server redirect instead of trying to patch the prefix middleware. This also adds a framework to add other server redirects since it seems we do not want them in Nginx.

Adding a new redirect rule with this framework can be done by:

1. adding a new entry to the `SERVER_REDIRECTS` map (with a short and meaningful key)
2. adding an entry (or more) in the `each()` array of the test case

### CODE REVIEW

**Comment by muffinresearch** [comment]
I think this should be fixed in the prefix middleware rather than introduce yet another place for redirects.

**Comment by willdurand** [comment]
> I think this should be fixed in the prefix middleware rather than introduce yet another place for redirects.

That makes sense, although I was not able to fix it today.. This patch is needed anyway (without the android redirect) because we want to add new redirects in the very near future (and likely move some permanent redirects from nginx to this codebase)

**Comment by bobsilverberg** [comment]
I've seen the discussion in the issue and it sounds like I should hold off reviewing this as possibly the approach is going to change?

**Comment by willdurand** [comment]
> I've seen the discussion in the issue and it sounds like I should hold off reviewing this as possibly the approach is going to change?

The approach to fix #8059, yes. You can probably reuse this patch for #8105 though :)

**Comment by muffinresearch** [comment]
> > I think this should be fixed in the prefix middleware rather than introduce yet another place for redirects.
> 
> That makes sense, although I was not able to fix it today.. I'll give it another try. This patch is needed anyway (without the android redirect) because we want to add new redirects in the very near future (and likely move some permanent redirects from nginx to this codebase)

In case it helps, I've proposed an independent prefix middleware patch to fix #8509 over here: https://github.com/mozilla/addons-frontend/pull/8120

**Pull request closed without merging**
