### PR TITLE
Add an rg .ignore file for better searching

### PR DESCRIPTION
**Pull request by kumar303**

### CODE REVIEW

**Comment by tofumatt** [comment]
So many dots! 😱

**Comment by kumar303** [comment]
@willdurand form your rg experience is there anything else we need to add?

**Comment by kumar303** [comment]
> So many dots!

heh, yeah. I considered removing `.ackrc` but maybe someone still needs ack for certain things.

**Comment by willdurand** [comment]
I mostly use the default config since it relies on `.gitignore` already. I guess this is fine.

**Pull request merged**
