### PR TITLE
Extract/Merge AMO locales

### PR DESCRIPTION
**Pull request by kumar303**

### CODE REVIEW

**Comment by kumar303** [comment]
@muffinresearch I'm still not clear on building debug locales. Does a PR like this [for extracting](https://github.com/mozilla/addons-frontend/blob/master/docs/i18n.md#extracting-newly-added-strings) need to include generated debug locales now?

**Comment by muffinresearch** [comment]
> @muffinresearch I'm still not clear on building debug locales. Does a PR like this for extracting need to include generated debug locales now?

Yes it does.

**Comment by muffinresearch** [comment]
Looks like this has bit-rotted with incoming changes. In general when this happens it can be easier to start-over and run the commands from master.

**Comment by kumar303** [comment]
No worries. I moved it to https://github.com/mozilla/addons-frontend/pull/2542

**Pull request closed without merging**
