### PR TITLE
I7478 remove enableFeatureHomeHeroGuides feature flag

### LINKED ISSUE #7478: Remove `enableFeatureHomeHeroGuides` feature flag (feature adopted)
We can probably remove the code for the `enableFeatureHomeHeroGuides` feature flag now that everything works fine. We could also remove the old home components that are not used anymore.

### PR DESCRIPTION
**Pull request by rebmullin**
fixes #7478

### CODE REVIEW

**Comment by rebmullin** [comment]
@willdurand, this is related to these changes? how can I see this error locally?

**Comment by willdurand** [comment]
> @willdurand, this is related to these changes? how can I see this error locally?

I dont see it when switching to another branch so... I don't know. Don't you see it in the console logs (of `yarn amo:dev`)?

**Comment by rebmullin** [comment]
hmm, I don't see any errors in the terminal so not sure why you are seeing this :/

**Comment by willdurand** [comment]
ah sorry, it looks like I had a proxy running in parallel, which was causing network issues...

**Pull request merged**
