### PR TITLE
fix: More extensions by author_name - section

### PR DESCRIPTION
**Pull request by tsl143**
Fixes: #3176 

**Before/After** 
screen shot 2017-09-19 at 10 33 13 pm
screen shot 2017-09-19 at 10 32 53 pm

### CODE REVIEW

**Comment by muffinresearch** [comment]
@tsl143 thanks for the pathc. Please can you add some details with rationale for the approach taken? This will help anyone not very familiar with CSS grids (myself included) to understand the fix (and learn something along the way) 👍

**Comment by tsl143** [comment]
@muffinresearch I too am trying to understand the CSS-grids (and I am loving it:) )
I followed https://css-tricks.com/snippets/css/complete-guide-grid/#article-header-id-26
So for this issue refer `grid-row: <start-line> / <end-line> | <start-line> / span <value>;`
Here we are following second pattern `grid-row: <start-line> / span <value>;`,
Initially `.AddonMoreInfo` was in 4th line, now we have 5 lines(boxes) So I gave it last line number that is  `grid-row: 5 / span 1;`

Hope that helps.

**Comment by muffinresearch** [comment]
If we specify something to be on the 5th line what happens if the thing that should be 4th line doesn't render e.g. if for that add-on data is missing?

**Comment by tsl143** [comment]
It will auto adjust, taking the last line for row consideration ie. 4th row.

**Comment by tofumatt** [comment]
Oddly I'm still not seeing these being loaded at all. I wonder if this is related to #3130?

**Comment by tofumatt** [comment]
Oh wait, maybe it's related to a weird API bug where versions 57+ are adding in the `appversion=57` param to any search. I bet that's it.

**Pull request merged**
