### PR TITLE
Fixes #5146

### LINKED ISSUE #5146: Link to Manage Firefox Accounts is missing from the Edit profile page
STR

1. Log in to AMO-dev
2. Click on Edit profile from the user menu
3. Check the data available on the Account card

Actual result:
There is no link to redirect the user on the Manage Firefox Account page

Expected result:
A link to Manage Firefox Account should be present on the edit profile page. This was a useful feature that was available on the legacy pages. 

Notes:
- reproduced on AMO dev with FF60 Win10x64

image

### PR DESCRIPTION
**Pull request by rishabh-bansal**
* [x] This PR relates to an existing open issue and there are no existing
      PRs open for the same issue.
* [x] Add `Fixes #ISSUENUM` at the top of your PR.
* [x] Add a description of the the changes introduced in this PR.
* [x] The change has been successfully run locally.
* [] Add tests to cover the changes added in this PR.
* [x] Add before and after screenshots (Only for changes that impact the UI).

Now it shows link to manage firefox accounts!

screen shot 2018-05-31 at 7 23 10 pm

### CODE REVIEW

**Comment by rishabh-bansal** [comment]
@willdurand  I'm facing difficulty in making test. Can you please help me out with this issue?

**Comment by willdurand** [comment]
> @willdurand I'm facing difficulty in making test. Can you please help me out with this issue?

You can create a test case that ensures there is a link displayed. It could be done in this test case I think: https://github.com/mozilla/addons-frontend/blob/master/tests/unit/amo/components/TestUserProfileEdit.js#L114.

I also think we should not display this link if `isEditingCurrentUser` is `false`. In addition, I don't think we should be using a `<label>` but a `<p>`.

**Comment by willdurand** [comment]
Hey @rishabh-bansal, do you need help here?

**Comment by rishabh-bansal** [comment]
@willdurand won't be able to take this up! Sorry! :/

**Pull request closed without merging**
