### PR TITLE
chore: Update homepage content

### LINKED ISSUE #4163: 25 January homepage content programming
For the **Thursday, 25 January** push, please update the AMO homepage programming in accord with what's outlined [here](https://docs.google.com/document/d/1g4RuGKW__eTHNd277rKPMM46ygonXzW68jSs2OXEkPM/edit#heading=h.e9p8yhnuv39m).

@EnTeQuAk @muffinresearch @diox

### PR DESCRIPTION
**Pull request by tofumatt**
Close #4163.

### Before

screenshot 2018-01-22 18 34 04

### After

screenshot 2018-01-22 18 41 13

### CODE REVIEW

**Comment by muffinresearch** [comment]
Not sure it came in via this patch but would be nice to fix these duplicated headings:

add-ons_for_firefox

**Comment by tofumatt** [comment]
Yeah... I don't think that's related to this patch and I think in general this homepage code is a bit... clunky. I think it could use a refactor in general. 🤔

**Comment by muffinresearch** [comment]
> Yeah... I don't think that's related to this patch and I think in general this homepage code is a bit... clunky. I think it could use a refactor in general. 🤔

Probably something to leave until we connect up to the admin tools.

**Comment by muffinresearch** [comment]
It seems possible now to have the same colour in multiple places:

add-ons_for_firefox

**Comment by tofumatt** [comment]
> It seems possible now to have the same colour in multiple places:

Looks like the wrong screenshot was attached 😅

**Comment by muffinresearch** [comment]
> Looks like the wrong screenshot was attached 😅

Yeah skitch was doing weird things - should be good now.

**Comment by tofumatt** [comment]
Ah, good catch. That might've even been possible before but I've tweaked around the colours now and it should be fine.

**Comment by muffinresearch** [comment]
Looks like there's an escaping issue on the collections page, the api appears to provide it to us that way:

See: https://addons.allizom.org/api/v3/accounts/account/mozilla/collections/dynamic-media-downloaders/

dynamic_media_downloaders_ _add-ons_for_firefox

**Comment by muffinresearch** [comment]
r+wc

**Comment by tofumatt** [comment]
Ah, that’s a bit weird... I don’t think we should treat that field as safe/escaped as it’s user input.

- Matt (Sent from mobile)

**Comment by muffinresearch** [comment]
> Ah, that’s a bit weird... I don’t think we should treat that field as safe/escaped as it’s user input.

Yeah I think it's an API bug

**Comment by muffinresearch** [comment]
@tofumatt as a workaround we could use the word "and" for that collection.

**Comment by muffinresearch** [comment]
I've filed https://github.com/mozilla/addons-server/issues/7368 for the escaping

**Comment by tofumatt** [comment]
I'm cool with changing the collection description but I'm not sure I have access to it. I just tried to change it and couldn't see where to 😢

**Comment by tofumatt** [comment]
I'm gonna merge this then as that bug is unrelated...

**Pull request merged**
