### PR TITLE
Fix codecov by re-creating yarn.lock and installing latest jest

### LINKED ISSUE #4823: Codecov is broken
Looks like coverage reports aren't being created and it's been broken for ~17 days.

It would be good for this to cause the test run to fail, otherwise this slips by unnoticed.  

Looking at the logs shows:

```
        Failed to write coverage reports:
        ERROR: TypeError: metrics.isEmpty is not a function
        STACK: TypeError: metrics.isEmpty is not a function
    at tableRow (/home/travis/build/mozilla/addons-frontend/node_modules/istanbul-reports/lib/text/index.js:133:27)
    at TextReport.onSummary (/home/travis/build/mozilla/addons-frontend/node_modules/istanbul-reports/lib/text/index.js:188:15)
    at TextReport.onDetail (/home/travis/build/mozilla/addons-frontend/node_modules/istanbul-reports/lib/text/index.js:193:17)
    at Visitor.(anonymous function) [as onDetail] (/home/travis/build/mozilla/addons-frontend/node_modules/istanbul-lib-report/lib/tree.js:34:30)
    at ReportNode.Node.visit (/home/travis/build/mozilla/addons-frontend/node_modules/istanbul-lib-report/lib/tree.js:123:17)
    at /home/travis/build/mozilla/addons-frontend/node_modules/istanbul-lib-report/lib/tree.js:116:23
    at Array.forEach (<anonymous>)
    at visitChildren (/home/travis/build/mozilla/addons-frontend/node_modules/istanbul-lib-report/lib/tree.js:115:32)
    at ReportNode.Node.visit (/home/travis/build/mozilla/addons-frontend/node_modules/istanbul-lib-report/lib/tree.js:126:5)
    at /home/travis/build/mozilla/addons-frontend/node_modules/istanbul-lib-report/lib/tree.js:116:23
```

### PR DESCRIPTION
**Pull request by muffinresearch**
Fixes  #4823

### CODE REVIEW

**Comment by bobsilverberg** [comment]
Interesting. Why did this fix it?

**Comment by muffinresearch** [comment]
@bobsilverberg see https://github.com/facebook/jest/issues/5772 for details

**Comment by muffinresearch** [comment]
Looks to have worked: https://codecov.io/gh/mozilla/addons-frontend/commit/f9d0384a853b7e06c6701cef93e9d34272fb5b4f

**Comment by bobsilverberg** [comment]
Nice, thanks @muffinresearch!

**Pull request merged**
