### PR TITLE
Add missing Manage FireFox Account link and aside description

### LINKED ISSUE #5146: Link to Manage Firefox Accounts is missing from the Edit profile page
STR

1. Log in to AMO-dev
2. Click on Edit profile from the user menu
3. Check the data available on the Account card

Actual result:
There is no link to redirect the user on the Manage Firefox Account page

Expected result:
A link to Manage Firefox Account should be present on the edit profile page. This was a useful feature that was available on the legacy pages. 

Notes:
- reproduced on AMO dev with FF60 Win10x64

image

### PR DESCRIPTION
**Pull request by dominictwlee**
fixes #5146 

Added manage firefox account link and aside description as detailed in the mockup by @willdurand.

peek 2018-06-23 11-34

### CODE REVIEW

**Comment by willdurand** [comment]
Hi @dominictwlee, looks good but could you remove the aside paragraph?

**Comment by dominictwlee** [comment]
Yeah sure no problem, I must have misinterpreted the issue, will get it fixed right away.

**Comment by willdurand** [comment]
> @willdurand Yeah sure no problem, I must have misinterpreted the issue, will get it fixed right away.

No worries, the mock-up was misleading. We only want to fix the link in the issue, not the rest of the card.

I also think this link should only be displayed when `isEditingCurrentUser` is `true`.

**Comment by willdurand** [comment]
@dominictwlee awesome! I pushed a minor update but good job!

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev with FF60, Win10x64 and Android 7.0

An issue regarding link redirection was fond and filed separately - see #5390

[1] edited user logged in
image

[2] edited user logged out
image

**Pull request merged**
