### PR TITLE
Theme with no author causing layout issues

### LINKED ISSUE #2073: Theme with no author causing layout issues
Steps to reproduce:
1. Search the theme "Eyes in the clouds" while in AMO-stage using your device - https://addons.allizom.org/en-US/android/search/?q=eyes+in+the+coulds

Expected results:
There are no displayed or layout issues.

Actual results:
Theme has no author. 

Notes/Issues:
- having no author causes layout issues in listing pages for that theme.
Verified on FF52(Android 6.0.1). Issue is reproducing all around AMO servers.
Screenshot for this issue:

### PR DESCRIPTION
**Pull request by tsl143**
Fixes #2073

### CODE REVIEW

**Comment by tsl143** [comment]
`.SearchResult-users` was inline element so `clear: both` doesnt work if there was no `.SearchResult-author` so this is fallback plan if there is no author.

**Comment by muffinresearch** [comment]
@tsl143 thanks for the patch! Please could you add before and after screenshots to the pr?

**Comment by tsl143** [comment]
Apologies for not uploading (I will make sure from next time to avoid delays)

**before**
before

**After**
after

**Comment by muffinresearch** [comment]
Thanks @tsl143!

**Pull request merged**
