### PR TITLE
Cleanup disco

### PR DESCRIPTION
**Pull request by willdurand**
Refs #1260

---

- move to directory-based components
- remove the `containers/` directory
- move scss files next to their components

### CODE REVIEW

**Comment by willdurand** [comment]
> Also just checking..was it officially decided to remove the container dirs and just move everything to components?

Yes, we don't use the `containers/` dir anymore.

> I still see an image in the disco/img dir. can we move that its respective dir? It looks like the DiscoPane component uses this, right?

let me check

**Comment by willdurand** [comment]
> I still see an image in the disco/img dir. can we move that its respective dir? It looks like the DiscoPane component uses this, right?

good idea!

**Comment by rebmullin** [comment]
@willdurand, I see some videos here too. Should we do the same as we do for images (put in the components dir) or what do you think?

**Comment by willdurand** [comment]
> @willdurand, I see some videos here too. Should we do the same as we do for images (put in the components dir) or what do you think?

Good catch, although I'll have to remove the video in #5323

**Pull request merged**
