### PR TITLE
Scroll restoration

### LINKED ISSUE #1323: Scroll position is maintained for new pages
### Describe the problem and steps to reproduce it:

* Visit https://amo.addons-dev.allizom.org/en-GB/firefox/ in responsive mode.
* Make a search e.g. "foo" https://amo.addons-dev.allizom.org/en-GB/firefox/search/?q=foo
* Scroll down and click one of the last results

### What happened?

The details page is loaded at the same scroll position as the click:

e.g: 

add-ons_for_firefox

### What did you expect to happen?

The scroll position should be the top of a new page after navigating. However, clicking back should keep the original scroll position.

### PR DESCRIPTION
**Pull request by muffinresearch**
Fixes #1323

### CODE REVIEW

**Comment by tofumatt** [comment]
Oh, one question, where does this scroll to? I'd think it'd make more sense if we loaded new pages just under the search bar, especially on mobile. Loading with the header in view on the page load isn't as useful to me.

**Comment by tofumatt** [comment]
What I mean is scrolling to `.App-content` (we could add an ID if needed) would be a lot better that just to the top of the page.

**Comment by muffinresearch** [comment]
> What I mean is scrolling to .App-content (we could add an ID if needed) would be a lot better that just to the top of the page.

That would be weird though since that's not what a browser would do.

**Comment by muffinresearch** [comment]
> (we could add an ID if needed)

If we want a fragment id and use that in the detail links - then that should be possible but that's out of scope for the purposes of this patch.

**Comment by tofumatt** [comment]
> That would be weird though since that's not what a browser would normally do which is the behaviour that this middleware is providing.

Fair enough. It feels like the proper "mobile" experience (thinking about how mobile app/browser toolbars will get out of the way when navigating through an app, and the user can scroll bar up for the search bar). Anywho, out of scope, you're right 😄

**Pull request merged**
