### PR TITLE
Set min-height on the Hero link, not the container

### PR DESCRIPTION
**Pull request by willdurand**
Before:

screen shot 2017-10-27 at 20 42 49

After:

screen shot 2017-10-27 at 20 38 15

### CODE REVIEW

**Comment by kumar303** [comment]
Your *after* screenshot shows a stretched download button but I don't see it locally with the patch.

**Comment by kumar303** [comment]
Is there an issue logged about this? I can't quite tell what it was fixing.

**Comment by willdurand** [comment]
Yes I noticed that on the screenshot, I think it is a HMR glitch... Could not reproduce and the change cannot impact that part of the UI anyway.

**Comment by willdurand** [comment]
No, no issue. It fixes an issue on browsers other than Firefox. The text on the small heros should be aligned on the bottom.

**Pull request merged**
