### PR TITLE
Add tox support for running UI tests

### PR DESCRIPTION
**Pull request by davehunt**
Replaces #887

### CODE REVIEW

**Comment by muffinresearch** [comment]
I wonder if it would make much difference if the tox setup only ran when tox is being run as opposed to tox etc being installed for each test in the matrix?

**Comment by muffinresearch** [comment]
r+wc

**Comment by muffinresearch** [comment]
@davehunt is this ready to land? I added one additional comment above but otherwise it looks good to me.

**Comment by davehunt** [comment]
@muffinresearch I agree with your comment but haven't had time to address it - I'm in a work week, so might not have much time to focus on this until next week. If you're happy to merge and then address your comments in a separate patch, that works for me too.

**Comment by muffinresearch** [comment]
@davehunt yep, may as well ship it and I'll file an issue for optimising the deps.

**Pull request merged**
