### PR TITLE
renaming fakeRouterLocation helper

### LINKED ISSUE #5736: Use `createFakeLocation()` instead of `fakeRouterLocation()` everywhere
The `fakeRouterLocation()` helper should be renamed to `createFakeLocation()`.

### PR DESCRIPTION
**Pull request by championshuttler**
Fixes #5736 

It should work fine, did not test locally :/ , my laptop still in repairing , using friend's laptop

### CODE REVIEW

**Comment by willdurand** [comment]
Hey @championshuttler, #5652 has been merged and you can see many conflicts. I was not able to rebase your branch so I guess we need to re-do the work on the new `master` version.

**Comment by championshuttler** [comment]
Hi, I will either rebase it or create a new PR as soon as I got  laptop of
my friend :P

**Comment by willdurand** [comment]
closing in favor of #5753

**Comment by championshuttler** [comment]
Thanks @willdurand for doing this , i just opened this PR to close :P

**Pull request closed without merging**
