### PR TITLE
Fix: RtL-LtR const changes #3362

### LINKED ISSUE #3362: i18n `getDirection()` helper should rely on constants
In `core/i18n/utils`, the `getDirection()` function should not use hardcoded values for `ltr` and `rtl` because then we need to test with the hardcoded values when using this helper:

https://github.com/mozilla/addons-frontend/blob/92b83273ba0c86ab750e92faf1c8e5a50c033aa8/src/core/i18n/utils.js#L104-L106

We should rather have `LTR` and `RTL` as constants, and use them. When working on this issue, please "grep" for `'rtl'`, `'ltr'` and `getDirection()` and update the code accordingly.

### PR DESCRIPTION
**Pull request by PhillypHenning**
Please delete anything that isn't relevant to your patch.
* [x] Add `Fixes #ISSUENUM` at the top of your PR.
* [x] Add a description of the the changes introduced in this PR.
* [x] The change has been successfully run locally.

Fixes #3362 

Description
Changed 'rtl' and 'ltr' strings in `src/core/i18n/utils.js` to constants. 

Test coverage
* [x] yarn lint
* [x] yarn test-once

### CODE REVIEW

**Comment by willdurand** [comment]
Hi @PhillypHenning, need help to finish this PR? Let me know!

**Comment by willdurand** [comment]
Hi @PhillypHenning, do you need help here?

**Comment by PhillypHenning** [comment]
Hey @willdurand, I just saw this, no problem I will make the changes tomorrow night and update!

**Comment by PhillypHenning** [comment]
Hey @tofumatt 
I have made the necessary changes to all js files that contain the strings 'ltr' or 'rtl' as requested however I notice a few scss and json files that contain the string as well. 

Would either of these file types need to contain the constant change as well?

**Comment by tofumatt** [comment]
There was a new PR opened for this issue so I'm closing this one.

**Pull request closed without merging**
