### PR TITLE
Remove the admin app

### PR DESCRIPTION
**Pull request by kumar303**
Fixes https://github.com/mozilla/addons-frontend/issues/2373

### CODE REVIEW

**Comment by kumar303** [comment]
@muffinresearch d'oh. We'd need to bump the coverage threshold down to to 93% for this since so much code was deleted.

**Comment by muffinresearch** [comment]
> @muffinresearch d'oh. We'd need to bump the coverage threshold down to to 93% for this since so much code was deleted.

I think it's more that the test coverage decreased since we are setup to not allow decreases at all. 

Would it take much to cover the missing parts?

**Comment by kumar303** [comment]
> Would it take much to cover the missing parts?

I haven't looked into it but it would be annoying to take time away from more pressing code quality issues. I'd like to do it eventually, for sure.

**Comment by muffinresearch** [comment]
> I haven't looked into it but it would be annoying to take time away from more pressing code quality issues. I'd like to do it eventually, for sure.

If you want to leave it as a follow-up then it's fine, but I would have thought that 0.4% drop should not amount to too many lines needing coverage.

r+wc

more-red-than-green-award-sm

**Comment by tofumatt** [comment]
> More red than green

An understatement. 👍

**Pull request merged**
