### PR TITLE
Removed the "no users" metadata entry for only search tools (on add-o…

### LINKED ISSUE #7316: Hide "no users" metadata entry for search tools (on add-on detail pages)
Based on: https://github.com/mozilla/addons/issues/819.

---

We do not have any "install data" for search tools so we always show add-ons with "no users". Let's hide this message for search tools as it conveys a negative impact for no reason.

### PR DESCRIPTION
**Pull request by twisted-sres**
Fixes #7316 
For search tools
screenshot from 2019-01-21 19-01-37
For others
screenshot from 2019-01-21 19-02-06

### CODE REVIEW

**Comment by twisted-sres** [comment]
Now I've used a better approach for the issue, and it's working, please review

**Comment by twisted-sres** [comment]
@willdurand please review

**Comment by twisted-sres** [comment]
Thanks! If there is anything else that I could work on, please let me know

**Comment by caitmuenster** [comment]
Thanks for the patch, @twisted-sres! We've added your contribution to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition). 

Would you be interested in creating a profile for mozillians.org?  I'd be happy to vouch for you!

**Pull request merged**
