### PR TITLE
Fixes #4633: changed color of "Download Firefox" message bar

### LINKED ISSUE #4633: Change "Download Firefox" message bar from grey to green
I'd rather we A/B test grey vs. green on the message bar, but since we can't let's just go with [the green style](https://design.firefox.com/photon/components/message-bars.html#color-2) for the "Download Firefox" prompt for non-Fx users.

screen shot 2018-03-23 at 1 46 28 pm

### PR DESCRIPTION
**Pull request by svitlana-galianova**
Hello, 
I have changed the color of the "Download Firefox" message bar from the grey to green, as requested in #4633. Here is a screenshot of how the message looks right now:
screen shot 2018-03-25 at 8 34 06 pm

### CODE REVIEW

**Comment by SeanPrashad** [comment]
Good to see you here @svitlana-galianova 😁🖖🏽Before the devs get here, we should fix up that one failing test that Travis is reporting:

```travis
Summary of all failing tests
FAIL tests/unit/amo/components/TestAddonCompatibilityError.js
  â— /home/travis/build/mozilla/addons-frontend/tests/unit/amo/components/TestAddonCompatibilityError.js â€º renders a generic notice for non-Firefox browsers

    Expected <Notice> "type" prop values to match but they didn't.
    Expected: [33mtype[39m[90m:[39m [33m[90m"generic"[33m[39m
    Actual: [33mtype[39m[90m:[39m [33m[90m"success"[33m[39m
      
      at Object.<anonymous> (tests/unit/amo/components/TestAddonCompatibilityError.js:79:74)


Test Suites: 1 failed, 196 passed, 197 total
Tests:       1 failed, 2711 passed, 2712 total
Snapshots:   0 total
Time:        235.125s
Ran all test suites.
```

With that brand spanking new colour, you'll have to update the [old test](https://github.com/mozilla/addons-frontend/blob/master/tests/unit/amo/components/TestAddonCompatibilityError.js#L78) to reflect it!

**Comment by svitlana-galianova** [comment]
Wow! I didn't know I was getting a personal mentor as well! Thanks, @SeanPrashad

**Comment by tofumatt** [comment]
Eventually the new bar should have a button link on the right hand side instead of the inline one, but this covers the original issue and works for me! 😄 

Thanks!

**Comment by caitmuenster** [comment]
Thanks so much, @svitlana-galianova! Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition#March_2018). 

Would you be interested in creating an account on [mozillians.org](https://mozillians.org/)? I'd be happy to vouch for you!

**Comment by svitlana-galianova** [comment]
@caitmuenster Thank you! And here is my mozillian account: https://mozillians.org/en-US/ 
@tofumatt If you have an open issue for implementing those changes/are going to create it, please include me there, I would love to help!

**Comment by caitmuenster** [comment]
Yay! You're vouched. :) Welcome onboard! I look forward to seeing you around the project!

**Pull request merged**
