### PR TITLE
Test case is working for the issue #7702

### LINKED ISSUE #7702: Wrong Link to Dictionary for Hindi Language
### Describe the problem and steps to reproduce it:

Go to https://addons.mozilla.org/en-US/firefox/language-tools/

### What happened?

Check the Dictionary listed for Hindi Language, right now its Hiligaynon spell checker which is wrong

### What did you expect to happen?

Correct Dictionary for Hindi Language should be listed.

### Anything else we should know?

image

### PR DESCRIPTION
**Pull request by Shubhamchinda**
Fixes #7702

Checked if the hiliguyon spell checker is showing or not above the hindi spell checker.
@willdurand Test case is working now.

### CODE REVIEW

**Comment by muffinresearch** [comment]
@Shubhamchinda great, so with this failing test you can now apply the suggested fix and see if that gets it to pass - see https://github.com/mozilla/addons-frontend/issues/7702#issuecomment-479508741 for a suggested patch.

**Comment by Shubhamchinda** [comment]
@muffinresearch I've already checked it with the fix, it's working fine.

**Comment by muffinresearch** [comment]
@Shubhamchinda can you add that commit to this PR to make a complete patch?

**Comment by Shubhamchinda** [comment]
@muffinresearch Done!

**Comment by willdurand** [comment]
@Shubhamchinda could you allow me to push to your branch?

**Comment by Shubhamchinda** [comment]
@willdurand Sure man!

**Comment by willdurand** [comment]
heh. I changed the commit message but it did not work apparently :/ anyway...

---

Thanks @Shubhamchinda, great work! /cc @caitmuenster

**Comment by Shubhamchinda** [comment]
Thanks @willdurand ! I hope my contribution helped. I'm new to the open source, I want to contribute more. Any suggestions would be appreciated.

**Comment by willdurand** [comment]
You can find issues by looking at the [opened `contrib: welcome` issues](https://github.com/mozilla/addons-frontend/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22contrib%3A+welcome%22).

**Comment by caitmuenster** [comment]
Thanks so much for the patch, @Shubhamchinda! 🎉 Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition). 

Welcome onboard! I look forward to seeing you around.

**Pull request merged**
