### PR TITLE
Fixed install button misalignment on guide page

### LINKED ISSUE #8324: Install button misaligned on guides page when add-on is not recommended
This is a follow-up to PR #8315. If the Recommended Badge is not displayed, due to an add-on not being recommended, the Install Button is still center-aligned with the add-on description, rather than being center-aligned with the entire contents of the card.

We do not expect there to ever be any add-ons on the guides page that are not recommended, but we should probably address this in case there ever are.

Here's how it looks now, when the badges are missing:

Screenshot 2019-07-16 12 22 49

And here's how it looked before fixing the badge alignment issue:

Screenshot 2019-07-16 12 24 01

### PR DESCRIPTION
**Pull request by Shubhamchinda**
Fixes #8324 

**After Fix :** 

Screenshot (187)

### CODE REVIEW

**Comment by willdurand** [comment]
@Shubhamchinda what would happen if the add-on has a recommended badge? You can open http://localhost:3000/en-US/firefox/guides/enhance-your-media-experience/ locally for example.

**Comment by Shubhamchinda** [comment]
@willdurand 
I saw that with the recommeded badge on, the badge is showing on the right side. See below

Screenshot (189)

**After Fix :**
Screenshot (190)


Is it the layout you guys wanted?

**Comment by willdurand** [comment]
> Is it the layout you guys wanted?

nope, we'd like to keep things as is when there are both the button and the badge:

Screen Shot 2019-07-22 at 08 59 39

**Comment by Shubhamchinda** [comment]
> nope, we'd like to keep things as is when there are both the button and the badge:

Ohh, Okay.
I think these changes are a quick fix for the issue. Since, same CSS is applied to card without checking the condition of recommended badge.

**With badge :** 
Screenshot (198)

**Without badge :**
Screenshot (197)

Please let me know if changes are to be done in CSS.
Thanks.

**Comment by bobsilverberg** [comment]
@Shubhamchinda Sorry, but we have decided this doesn't really need to be fixed, so we've closed the issue and I'm going to close this PR as well. Thanks for your efforts on it.

**Comment by Shubhamchinda** [comment]
No problem @bobsilverberg . I'm here to help, let me know if there's anything for me. I'll be happy to help, :)

**Pull request closed without merging**
