### PR TITLE
override apiHost when running tests

### LINKED ISSUE #1138: Prevent the test suite from ever calling a real API
### Describe the problem and steps to reproduce it:
- write a test for an action that calls the API
- forget to mock out the `callApi` method
### What happened?

This will attempt to make a real API request (depending on what server is configured). The result will probably be a harmless 401 Unauthorized since no real tokens are used in the test suite but this can cause slowness.
### What did you expect to happen?

It should not make any real API request at all even though it was a mistake not to mock the component.
### Anything else we should know?

(Please include a link to the page, screenshots and any relevant files.)

### PR DESCRIPTION
**Pull request by bjdixon**
- fixes #1138

### CODE REVIEW

**Comment by muffinresearch** [comment]
This doesn't fix #1138 since the disco pane tests are still set up to point to a real API.

**Comment by tofumatt** [comment]
Shoot, sorry.

**Comment by bjdixon** [comment]
I think there are a couple of tests in tests/server/disco/TestViews.js that fail unless they hit the API.

**Comment by tofumatt** [comment]
They’ll need to be fixed too then, in order to truly fix the issue. Hitting
the API minimally isn’t really that different than hitting it a lot :-)

**Comment by kumar303** [comment]
@bjdixon thanks for digging into this! I think the fix we need is to completely stub out `window.fetch` used in [callApi](https://github.com/mozilla/addons-frontend/blob/master/src/core/api/index.js) maybe in a [beforeEach](https://mochajs.org/#hooks) hook when the test suite [initializes](https://github.com/mozilla/addons-frontend/blob/master/tests/client/init.js). Perhaps there is a less fragile way to do it though, I haven't thought too hard on it.

> I think there are a couple of tests in tests/server/disco/TestViews.js that fail unless they hit the API.

This could be fixed in a separate issue. I filed https://github.com/mozilla/addons-frontend/issues/1138 mainly to fix the unit tests, which should never hit a real API.

**Pull request merged**
