### PR TITLE
Adding Nightly System Add-ons to the ignore list.

### PR DESCRIPTION
**Pull request by designakt**
Since updating this list I identified 4 more system add-ons in Nightly.

### CODE REVIEW

**Comment by muffinresearch** [comment]
Are these all present in a completely new profile?

**Comment by designakt** [comment]
@muffinresearch I did not check that. Why is that relevant?

**Comment by muffinresearch** [comment]
> @muffinresearch I did not check that. Why is that relevant?

Because that ensure they are there by default as opposed to something that got added via usage.

**Comment by designakt** [comment]
Why does that matter? Any system addon will be installed by us, without the user needing to know about addons. So even if it got added because of usage they still can be new addon users.

**Comment by muffinresearch** [comment]
> Why does that matter? Any system addon will be installed by us, without the user needing to know about addons. So even if it got added because of usage they still can be new addon users. 

But they should be present in a new profile created with that specific version of nightly too. Checking that makes sure there's nothing being added that shouldn't be.

**Comment by designakt** [comment]
I found a safer way to identify system add-ons:
in about:telemetry -> Environment -> Addons i can check for isSystem=true
So we can be sure the ones I added are system add-ons, no matter if they appear in a new profile or not.

**Pull request merged**
