### PR TITLE
Fix mozAddonManager initialization (fixes install switch)

### PR DESCRIPTION
**Pull request by kumar303**
Fixes https://github.com/mozilla/addons-frontend/issues/2636

There are two main problems I'm fixing:
* when a wrapped component gets updated with a new `addon` prop, the HOC wasn't querying the addon manager for data
* when a wrapped component is updated, the HOC was defined in a way where it did not have access to the new properties

### CODE REVIEW

**Comment by kumar303** [comment]
@tofumatt I tried not to change too much even though this code is a bit gnarly. This patch fixed the issue for me.

**Comment by kumar303** [comment]
Aw crap, this only fixed *showing* the install button. The install flow is still broken.

**Comment by tofumatt** [comment]
Alright, I'll wait to review until the flow is fixed too.

Matthew Riley MacPherson (sent from mobile)

**Comment by kumar303** [comment]
It should be ready for review now.

**Comment by kumar303** [comment]
The most helpful thing would be to test this out locally and make sure it's working -- we need to get it on dev ASAP. Tuesday is a US holiday.

@muffinresearch could you help test the patch too?

**Comment by tofumatt** [comment]
My flights were a bit delayed but I'm settled and such back home. I should be able to test tonight or tomorrow at the latest 👍

**Comment by tofumatt** [comment]
Just tested it quickly locally for extensions and themes–thus far seems all good. I'll have a look through the code ASAP, thanks for the quick patch.

**Comment by muffinresearch** [comment]
Just fixed the conflicts so I can try this out...

**Comment by muffinresearch** [comment]
Install looks to work running charles to fake a.m.o for both the amo and discovery apps.

**Pull request merged**
