### PR TITLE
Fixes #7529: Added 2px Margin Between Buttons

### LINKED ISSUE #7529: Cancel and Save buttons in the add/edit collection forms are too close together in some locales on mobile
STR:

1. Log in to AMO on a mobile device, or use the responsive design mode
2. Set your locale to `fr`
3. Observe the Cancel and Save buttons

Actual result:
Cancel and Save buttons are stuck together 

Expected result:
There is enough spacing between the Cancel and Save buttons

Notes:
- reproduced on all AMO servers with FF65, Win10x64 and Android 8.0
- the issue also applies to the Edit collection form

[1] mobile view - Create collection

image

[2] ~850px width - Create collection
image

[3] ~850px width - Edit collection
image

### PR DESCRIPTION
**Pull request by suhailsinghbains**
Added 2px Margin Between Buttons
image

### CODE REVIEW

**Comment by suhailsinghbains** [comment]
Hi
I wasn't able to Make Buttons width to be more, can you please help me with it.
image

**Comment by willdurand** [comment]
@suhailsinghbains I believe you want `width: 100%` on the buttons, no?

**Comment by suhailsinghbains** [comment]
Yes, I wanted to do that, but, it extends way too much on the larger screen :(

**Comment by willdurand** [comment]
> Yes, I wanted to do that, but, it extends way too much on the larger screen :(

Ah I see. I think we've done that for some other buttons. We need `width: 100%` on small screens and then we "reset" the `width` on larger screens.

**Comment by willdurand** [comment]
Thanks @suhailsinghbains, I slightly updated your patch but good job 👍

**Pull request merged**
