### PR TITLE
chore(package): update postcss-loader to version 2.0.6

### PR DESCRIPTION
**Pull request by tofumatt**
Closes #2354 
Closes #2363

### CODE REVIEW

**Comment by tofumatt** [comment]
Tested locally in dev mode and tested the production build script's CSS output: both are still auto-prefixing appropriately for AMO and not for Disco.

r?

**Comment by kumar303** [comment]
This needs some lint fixes

**Comment by tofumatt** [comment]
Ah shoot, right, there are a lot of linting errors I've fixed across branches that have popped up with dep updates :-/

**Comment by tofumatt** [comment]
Okay, updated and passes lint now.

**Pull request merged**
