### PR TITLE
Consistently use username as the user identifier in collections reducers and sagas

### LINKED ISSUE #5142: Consistently use one user identifier in collections reducers and sagas
While working on the "Delete a collection" feature, I discovered that we are inconsistently using either the string `username` or the numeric `userId` in different reducer and saga methods, and I see no reason to do so. All of the APIs are designed to accept either a numeric `userId` or a string `username`, and both are guaranteed to be unique to an individual user. We should update our code to either always use `userId` or always use `username` to remove the inconsistency and resulting confusion in the codebase.

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #5142 

I decided to use the string `username` as the identifier in all cases, rather than the numeric `userId`, mainly because of this [comment](https://github.com/mozilla/addons-frontend/blob/38c186ed9a33f950db1ebbeb09b6cb386fd9d1fd/src/amo/api/collections.js#L133), which has to do with the fact that we sometimes redirect to a URL and want that URL to be username-based.

Sorry for the large PR. It's *mostly* just direct changes from `userId` to `user` in a lot of places, but there are a few places I had to change some logic as well, mostly in the components.

### CODE REVIEW

**Comment by willdurand** [comment]
@bobsilverberg before I fully review this PR (which is a nice one 💪), why did you rename everything to `user` if we only pass the `username` everywhere? I thought we used `user` for both `userId` or `username` (because `userIdOrName` would be a bad variable name).

**Comment by bobsilverberg** [comment]
I used `user` because there was existing code that uses `user`, defined as a `string` when all we ever pass is `username`, so rather than change all the code, I figured I'd just keep `user` and do away with `userId`. I infer that you are suggesting I should have used `username` instead, and that definitely makes sense. I will update it tomorrow.

**Comment by bobsilverberg** [comment]
Ok, I changed everything to be `username`.

**Comment by willdurand** [comment]
@bobsilverberg do you also see lots of conflicts for this PR?

**Comment by bobsilverberg** [comment]
> do you also see lots of conflicts for this PR?

@willdurand Probably because I merged PR #5165. I'll rebase and fix those.

**Comment by bobsilverberg** [comment]
Ok @willdurand I have rebased and fixed the (large number of) conflicts, so this should be ready for a look.

**Comment by bobsilverberg** [comment]
Thanks @willdurand!

**Pull request merged**
