### PR TITLE
Update webpack, html-webpack-plugin and webpack-subresource-integrity

### PR DESCRIPTION
**Pull request by diox**
Fixes https://github.com/mozilla/addons-frontend/issues/11419

### CODE REVIEW

**Comment by diox** [comment]
We discussed the failures a little bit. There are 2 issues:
- The build breaking because `integrity` is missing for png, svgs and woff2 files. Our  `sriDataPlugin` errors out as a result.
- The tests breaking because of one `test_sriDataPlugin` failure. We aren't quite sure, but suspect the way we're invoking webpack manually in the test is wrong.

I'm going to look into all that. Maybe I'll end up replacing that `sriDataPlugin` entirely by https://github.com/webdeveric/webpack-assets-manifest, and removing SRI for the fonts.

**Comment by diox** [comment]
> * The tests breaking because of one `test_sriDataPlugin` failure. We aren't quite sure, but suspect the way we're invoking webpack manually in the test is wrong (for the failing case, the `app2.js` file is never created, and in all tests, we can see in the results that the generated bundle is empty)

Because webpack was in production mode, the missing files + the fact that they were only comments meant that data wasn't produced and that's why it was failing. I've added a couple checks to make this more obvious independantly of the `sriDataPlugin`.

**Review by bobsilverberg — APPROVED** [review]
Nice work on this. I actually thought to myself that maybe our test js files should have something other than a comment in them, but I didn't actually try making that change. 😛 

r+

**Comment by diox** [comment]
> I actually thought to myself that maybe our test js files should have something other than a comment in them, but I didn't actually try making that change.

For the record, I think the actual fix was to make the input files actually exist. But ensuring they are not just comments makes the bundle size non-0, which proves that the compilation executes correctly which then makes it more obvious where the problem lies.

I almost switched webpack mode to `none` instead, but I figured leaving it as it is would be better as it's closer to a real-life scenario.

**Pull request merged**
