### PR TITLE
WIP: Inline SVG files (fix #1207)

### LINKED ISSUE #1207: Use inline SVG for header so we can style it
As discussed here: https://github.com/mozilla/addons-frontend/pull/1194#discussion_r82698882

### PR DESCRIPTION
**Pull request by tofumatt**
This will inline all SVG files and include them using an `Icon` component instead of `::before` and `::after` CSS attributes. This will allow us to style them.

Right now I'm inlining them into the header of the page, but we should probably just build an SVG file of all the symbols and reference it instead.

### CODE REVIEW

**Comment by mstriemer** [comment]
```
 assets/.DS_Store                   | Bin 6148 -> 0 bytes
```

🙌

**Comment by tofumatt** [comment]
I don't even know how that snuck in there!

**Comment by muffinresearch** [comment]
Is is worth closing this one until we get a chance to come back to it if it's not in active review?

**Comment by tofumatt** [comment]
Indeed, closed for now.

**Pull request closed without merging**
