### PR TITLE
I6701 turn on home hero guides in dev

### PR DESCRIPTION
**Pull request by rebmullin**
fixes mozilla/addons#12569 

TODOs:
- ~~need to make sure guids/addons exist on stage too (do we need for stage yet?)~~ created a new issue mozilla/addons#12688 for stage 
- ~~find out if anyone else needs to be alerted to these changes (for uitests)~~

### CODE REVIEW

**Comment by willdurand** [comment]
> * need to make sure guids/addons exist on stage too

You mean -dev? We can probably ask @devaneymoz to make sure the addons with GUIDs exist in -dev and (soon -stage) for QA.

> * find out if anyone else needs to be alerted to these changes (for uitests)

I think that's fine. The uitests problem is with the uitests setup, not this feature.

**Comment by willdurand** [comment]
> I think that's fine. The uitests problem is with the uitests setup, not this feature.

That being said, QA should probably be aware. /cc @ioanarusiczki and @vcarciu

**Comment by rebmullin** [comment]
> You mean -dev? We can probably ask @devaneymoz to make sure the addons with GUIDs exist in -dev and (soon -stage) for QA.

Regarding dev - some of them existed already and the other ones I've actually added manually. altho these are the ones that say they're by me. Hopefully that's okay for dev..

Yep, we still need to do this for stage. if @devaneymoz can help..great, otherwise I can try to do it too. We just need to make sure it's ready for when we push to stage. 


> I think that's fine. The uitests problem is with the uitests setup, not this feature.

thanks @willdurand

**Comment by rebmullin** [comment]
Since is ready now, I am going to add a new file for the stage setup.

**Pull request merged**
