### PR TITLE
Issue #8632, Change link color

### LINKED ISSUE #8632: The View Site links on Android have the same color as the rest of the text
STR:
1. On an Android device the links  `<a href="https://youtu.be/w_lCi8U49mY">Click the following link </a>` or `  <a href="https://support.mozilla.org/en-US/kb/recommended-extensions-program">Visit SUMO </a>`

 could be more visible if they'd look like on Desktop 

Android 

Links are black

Desktop 

Links on desktop

This is reproducible on AMO dev with Android 8.0.0
Please note links without HTML format are interpreted as text.

### PR DESCRIPTION
**Pull request by virgilt**
fixes #8632

@willdurand I ran it locally and both desktop and android links are black. The links change color when they are clicked and you return the page once again. If you clear the browsing data, the color is back to black. Located class Notice-text, and change the link color.

### CODE REVIEW

**Comment by virgilt** [comment]
@willdurand Travis CI keeps failing FORCE_COLOR=0. Assuming this is because I am forcing the color for the links. Do I need to change the testing in order for it to pass?

**Comment by willdurand** [comment]
> @willdurand Travis CI keeps failing FORCE_COLOR=0. Assuming this is because I am forcing the color for the links. Do I need to change the testing in order for it to pass?

mmh no, it is because there are linter issues. Please run `yarn lint` locally.

**Comment by virgilt** [comment]
@willdurand All checks passed. Thank you so much for you help!

**Comment by virgilt** [comment]
@willdurand added your code to the patch

**Pull request merged**
