### PR TITLE
Update header to header spec

### PR DESCRIPTION
**Pull request by muffinresearch**
Fixes: #323

Before:
discover_add-ons

After:

discover_add-ons

### CODE REVIEW

**Comment by mstriemer** [comment]
I think the heading text looks nicer at 22px, the copy is definitely better though. Maybe we can leave the heading at 22px and @pwalm won't notice?

**Comment by muffinresearch** [comment]
I think let's do it to spec and ask UX if they want any changes when they look at the real thing in practice. 

Fwiw: re: the `h1` the headings in the mocks looked to have letter-spacing which I'd previously eye-balled so it's not just the font-size change here the letter-spacing is also removed back to the default.

**Comment by mstriemer** [comment]
Ah, yeah that's what it is. It looks cramped to me now.

**Comment by pwalm** [comment]
Let's stick with "After." The type looks more balanced. 👍

**Pull request merged**
