### PR TITLE
Fix for Issue #9411

### LINKED ISSUE #9411: The 'Learn more about permissions' button should always be visible on the Permissions card
Follow up for #7634 

### Describe the problem and steps to reproduce it:
1. Open the following extension detail page - https://addons.allizom.org/en-US/firefox/addon/many-files/
2. Scroll down to the Permissions card and look for the 'Learn more about permissions' button

### What happened?
The button is hidden in the `ShowMoreCard` 

### What did you expect to happen?
The button is always visible, i.e the user should not have to click on Read more to access the button

### Anything else we should know?
- a `ShowMoreCard` for Permissions was introduced when #7634 was fixed

### PR DESCRIPTION
**Pull request by Kushagraw12**
Fixes #9411

The 'Learn more about" button is now visible without having to click on the 'Read More' first, as described in the issue.

After screenshot:

87541121-65aace00-c6be-11ea-96d8-3c77a63a7236

### CODE REVIEW

**Comment by muffinresearch** [comment]
One nit with this approach is that with a longer list of permissions the button would still be hidden. 

@bobsilverberg what do you think, I'm wondering if this needs some UX input. It might be best to move the button to being a link in the card header or move it above the lists.

**Comment by Kushagraw12** [comment]
> One nit with this approach is that with a longer list of permissions the button would still be hidden.
> 
> @bobsilverberg what do you think, I'm wondering if this needs some UX input. It might be best to move the button to being a link in the card header or move it above the lists.

Should I try and remove the 'Read More' button only from all the cards that have permission buttons?
Do let me know, how I can fix it and make it better. 
Thanks!

**Comment by bobsilverberg** [comment]
> One nit with this approach is that with a longer list of permissions the button would still be hidden.
> 
> @bobsilverberg what do you think, I'm wondering if this needs some UX input. It might be best to move the button to being a link in the card header or move it above the lists.

I do think we need UX input, as it does sound like moving the button up above the list, or making it a link in the header, would be better than trying to make sure it "floats" inside the compressed box.  I'll update the issue and add it to the front-end meeting agenda.

**Comment by bobsilverberg** [comment]
@Kushagraw12 Thanks for your time on this. I'm going to close this PR as it doesn't really address the issue in a way that will work. The issue is on hold until we get some UX feedback, but feel free to keep following it, and to open up a new PR to address the new requirements once they are defined.

**Comment by Kushagraw12** [comment]
> @Kushagraw12 Thanks for your time on this. I'm going to close this PR as it doesn't really address the issue in a way that will work. The issue is on hold until we get some UX feedback, but feel free to keep following it, and to open up a new PR to address the new requirements once they are defined.

Okay. Thanks!
I will try to solve some other 'good-first issues'! 👍

**Comment by willdurand** [comment]
> I'll update the issue and add it to the front-end meeting agenda.

I wasn't aware of this meeting, could you invite me? :)

**Comment by willdurand** [comment]
> I'll update the issue and add it to the front-end meeting agenda.

@bobsilverberg I wasn't aware of this meeting, could you invite me? :)

**Comment by bobsilverberg** [comment]
> > I'll update the issue and add it to the front-end meeting agenda.
> 
> @bobsilverberg I wasn't aware of this meeting, could you invite me? :)

Sure, I just did.

**Pull request closed without merging**
