### PR TITLE
Capitalization fixes #7825 

### LINKED ISSUE #7825: The title of the version page does not match the mock-ups
The title of the "version page" should be "[extension name] version history".

Actual:

Expected:

The mock-ups below has a different case but we're not using it anywhere else in the site... So I guess it's better if we are consistent. We can still file an issue to change the case everywhere if that's beneficial.

Screen Shot 2019-04-03 at 14 35 21

### PR DESCRIPTION
**Pull request by mymindstorm**
Fixes #7825 

I can't add screenshots since my laptop isn't powerful enough to run staging and I'm travelling. The changes are so simple I doubt it really matters.

cc @willdurand

### CODE REVIEW

**Comment by mymindstorm** [comment]
I'm just realizing how many locale files there are, do I need to run a find+replace on all of those?

**Comment by willdurand** [comment]
> I'm just realizing how many locale files there are, do I need to run a find+replace on all of those?

No. It should only be applied to the JS files. Locale files are automatically updated.

**Comment by willdurand** [comment]
I think you need to revert the changes in the locale files.

**Comment by mymindstorm** [comment]
The tests are timing out for some reason? Doesn't seem to be just this commit.

**Pull request merged**
