### PR TITLE
disabling react/sort-comp globally

### LINKED ISSUE #5357: Disable ESLint rule `react/sort-comp` globally
The [`react/sort-comp` rule](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md) often forces us to either disable it or to write code we did not want to write in the first place (for example, adding attribute declarations in the middle of a class, not at the top of it).

We should disable this rule globally.

### PR DESCRIPTION
**Pull request by championshuttler**
Fixes #5357

### CODE REVIEW

**Comment by championshuttler** [comment]
I think I should remove `eslint-disable react/sort-comp` comment from all the files also as we are disabling it globally , no need to mention it again in code

**Comment by willdurand** [comment]
Indeed, removing the comments in the code would be nice!

**Comment by championshuttler** [comment]
Done ;)

**Comment by willdurand** [comment]
Thanks @championshuttler!

**Comment by championshuttler** [comment]
Hi, @willdurand just an off topic question how did you manage so many of GitHub notifications? 😝

**Comment by willdurand** [comment]
> Hi, @willdurand just an off topic question how did you manage so many of GitHub notifications? 😛

Emails disabled, and the notifications page always opened. I apply the "inbox zero" methodology, but for GH notifications :)

**Comment by championshuttler** [comment]
Cool, thank you so much. I never used this notifications page. and my inbox flooded with mails

**Pull request merged**
