### PR TITLE
[revert]: Reverted the changes committed in #9302

### LINKED ISSUE #9317: Revert changes to cursor on hover for selects
https://github.com/mozilla/addons-frontend/commit/dfea0f60130911847add4954c1f7a735ce2e1ae6 introduced some styles that applied a cursor change for `hover` for some `select` elements. This overrides the default browser styles, and does not do it for every `select` element, but just for some.

We don't know if we want to override the browser style like that, and if we do then we should do it universally for all `select`s.

We should revert that commit for now until that decision is made.

### PR DESCRIPTION
**Pull request by muskangupta-iitr**
Fixes #9317

Reverted all the changes committed in the #9302.

### CODE REVIEW

**Comment by muskangupta-iitr** [comment]
@willdurand @bobsilverberg I created a PR for reverting the changes :+1:

**Comment by willdurand** [comment]
Looks good. Did you use `git revert` to generate this commit?

**Comment by muskangupta-iitr** [comment]
@willdurand No, I created this manually 😅. Is it ok? Actually, I didn't knew about `git revert` command.

**Comment by willdurand** [comment]
> @willdurand No, I created this manually 😅. Is it ok? Actually, I didn't knew about `git revert` command.

It'd be better to use `git revert` (for the history). could you do that please?

**Comment by muskangupta-iitr** [comment]
> > @willdurand No, I created this manually sweat_smile. Is it ok? Actually, I didn't knew about `git revert` command.
> 
> It'd be better to use `git revert` (for the history). could you do that please?

Yes sure! I will update the PR with `git revert`.

**Comment by muskangupta-iitr** [comment]
@willdurand @bobsilverberg I have update the PR to revert the changes. Could you please review it? Also, @willdurand thanks for the suggestion as I learned something new from it. :)

**Pull request merged**
