### PR TITLE
Fixed My Collections container exceeding layout issue

### LINKED ISSUE #5426: My Collections container will fall outside the designated area if a collection name has an unbroken string
STR:

1, Log in to AMO -dev
2. Go to My Collections and select one of the collections to edit
3. Update the name by adding an unbroken string and Save the changes
4. Go back to My Collections and observe the page layout

Actual result:
Unbroken strings in collection names will push the container outside of the designated area

Expected result:
My Collections container should have a fixed position

Notes:
- this will also shrink the information card on the left, containing the Create Collection button
- reproduced on AMO-dev with FF60, WIn10x64

image

### PR DESCRIPTION
**Pull request by Shubhamchinda**
Fixes #5426 

**Before Fix :**

Screenshot (203)

**After Fix :**

Screenshot (202)

### CODE REVIEW

**Comment by muffinresearch** [comment]
I think we've had issues with `word-wrap: break-all` in the past because it will break a word when it wraps even though it does the right thing with a single un-broken string.

Please test with both an unbroken string and a set of words with spaces. 

We could probably use `overflow-wrap: break-word;` instead.

See also: 

- https://developer.mozilla.org/en-US/docs/Web/CSS/word-break
- https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

**Comment by Shubhamchinda** [comment]
Hey @muffinresearch , hope you're doing great.

> We could probably use `overflow-wrap: break-word;` instead but please test with both an unbroken string and a set of words with spaces.

Thanks a lot, I've tested it and yeah using ``` overflow-wrap: break-word;``` would be correct here as ```word-wrap: break-all``` is breaking single words as well.

> * https://developer.mozilla.org/en-US/docs/Web/CSS/word-break
> * https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap
 Thanks again for this. I'll update the PR.

**Comment by Shubhamchinda** [comment]
Hey @muffinresearch , I hope you're doing great.
 
> I think we've had issues with `word-wrap: break-all` in the past because it will break a word when it wraps even though it does the right thing with a single unbroken string.

Yeah, I tested it. ```word-wrap: break-all;``` is breaking the single words as well. 

> We could probably use `overflow-wrap: break-word;` instead but please test with both an unbroken string and a set of words with spaces.

I've test `overflow-wrap: break-word;` as well, but it's not working here. You can see in below image.

Screenshot (213)

Seeing this issue generating very often I tested ``` word-break : break-word;``` . I think we should use it everywhere as we're using different ```wrap``` everywhere. I've test the ` word-break: break-word` in PR #8337 too. It is working fine there as well. You can see below image fixed using `word-break`.

Screenshot (212)

**At colector's note page**

Screenshot (214)


> * https://developer.mozilla.org/en-US/docs/Web/CSS/word-break
> * https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

Thanks a lot. Let me know your thoughts on it. :)

**Comment by Shubhamchinda** [comment]
Hey @muffinresearch !

It's been a while since I heard back from you on this. I was wondering if [this](https://github.com/mozilla/addons-frontend/pull/8366#issuecomment-515551586) is the correct approach.
Thanks!

**Pull request merged**
