### PR TITLE
Fetch userCollections after adding add-on 

### LINKED ISSUE #5723: If an addon is added to a collection from its details page, it will be displayed only after refreshing the collection page.
Steps to reproduce:
1. Be sure that you already have a collection with some addons and that you already opened it at least one time
2.Open an addon details page and add the addon to the collection from Step1
3.Go to "View my collections" page and select the collection from Step1

Expected results:
The add-on added in Step2 is present inside collection

Actual results:
The add-on is displayed only after a page refresh

Please see a video with the issue : 
collectionrefresh

### PR DESCRIPTION
**Pull request by motiko**
Fixes #5723 

Fetch userCollections after adding  add-on to collection from add-on page.

### CODE REVIEW

**Comment by motiko** [comment]
@bobsilverberg Anything preventing this from being merged?

**Comment by bobsilverberg** [comment]
Sorry for the delay in looking at this @motiko, and thanks for taking a look at this. Unfortunately this patch does not work. `fetchUserCollections` just fetches and loads the aggregate data for all user collections (e.g., the name of the collection, the number of items, etc.), but what we need is for the details of the specific collection that was just added to to be updated. I believe this is all described at https://github.com/mozilla/addons-frontend/issues/5723#issuecomment-414391602.

As an aside, you should be able to test your patches locally by running `yarn amo:dev`, and if you do that with this patch you'll see that it does not resolve the issue reported at https://github.com/mozilla/addons-frontend/issues/5723#issue-344401750.

**Comment by bobsilverberg** [comment]
@motiko Just wondering if you are planning on working on this some more. I added some comments to guide you at https://github.com/mozilla/addons-frontend/pull/8399#issuecomment-527470972.

**Comment by motiko** [comment]
@bobsilverberg thank you for your comments. I will try again this weekend.

**Comment by bobsilverberg** [comment]
Hi @motiko, just checking in again. Is there anything I can help with?

**Comment by bobsilverberg** [comment]
This has been outstanding without any updates for over a month, so I'm going to close it. @motiko if you decide to take it up again I'll be happy to review a new pull request.

**Pull request closed without merging**
