### PR TITLE
fix: add Android category icons

### PR DESCRIPTION
**Pull request by tsl143**
Fixes: #3379 
Before:
screen shot 2017-10-07 at 6 10 02 pm

After:
screen shot 2017-10-07 at 6 09 38 pm

Also this PR will take care of #3377 (`.Icon-experimental` was overrided by https://github.com/mozilla/addons-frontend/blob/master/src/ui/components/Icon/experimental.svg so added `category` prefix to all category header icons, now the class name will be like `.Icon-category-experimental` so no conflict)

### CODE REVIEW

**Comment by willdurand** [comment]
Heh sorry, I have done that differently locally and that's why I was assigned 😶

**Comment by tsl143** [comment]
@willdurand , ohh its okay,
You can merge any one and close the issue then :)

**Comment by willdurand** [comment]
@tsl143 I'll try to keep track of your work ;-)

**Comment by tofumatt** [comment]
Sounds like this will be handled elsewhere so I'm just gonna close this PR, but please re-open if I'm mistaken 😄

**Pull request closed without merging**
