### PR TITLE
Update full-icu

### PR DESCRIPTION
**Pull request by willdurand**
Fixes https://github.com/mozilla/addons-frontend/issues/9350

---

I am not sure what needs to be done to fix the issue with Travis CI but having an up-to-date `full-icu` package seems like a good idea.

### CODE REVIEW

**Comment by bobsilverberg** [comment]
Just wondering, how did you generate those lock file changes?

**Comment by willdurand** [comment]
> Just wondering, how did you generate those lock file changes?

I ran `yarn remove full-icu && yarn add full-icu`

**Comment by bobsilverberg** [comment]
> > Just wondering, how did you generate those lock file changes?
> 
> I ran `yarn remove full-icu && yarn add full-icu`

Ah, thanks!

**Comment by willdurand** [comment]
@bobsilverberg so I cleared the (yarn) cache on Travis CI and it seems to fix the issue. I am not sure whether we want to merge this patch, but I guess it wouldn't hurt. You tell me :)

**Comment by bobsilverberg** [comment]
> @bobsilverberg so I cleared the (yarn) cache on Travis CI and it seems to fix the issue. I am not sure whether we want to merge this patch, but I guess it wouldn't hurt. You tell me :)

1. How did you clear the yarn cache on Travis?
2. Are you saying that clearing the cache resolved the problem, even without these changes? If so, then it seems like it might be safer not to land this, as monkeying around with lock files makes me nervous. Having said that, if you think it's better to have this change in, I'm fine with that too.
3. Aren't you supposed to be on holiday?

**Comment by willdurand** [comment]
> * How did you clear the yarn cache on Travis?

There is a "clear" button in https://travis-ci.org/github/mozilla/addons-frontend/caches

> * Are you saying that clearing the cache resolved the problem, even without these changes? If so, then it seems like it might be safer not to land this, as monkeying around with lock files makes me nervous. Having said that, if you think it's better to have this change in, I'm fine with that too.

I don't have a strong opinion, I did not manually update the lockfile so I am fairly confident these changes are fine. The Renovate PR to update the lockfile will likely do the same thing anyway.

> * Aren't you supposed to be on holiday?

🤓

**Comment by bobsilverberg** [comment]
> 
> > * Are you saying that clearing the cache resolved the problem, even without these changes? If so, then it seems like it might be safer not to land this, as monkeying around with lock files makes me nervous. Having said that, if you think it's better to have this change in, I'm fine with that too.
> 
> I don't have a strong opinion, I did not manually update the lockfile so I am fairly confident these changes are fine. The Renovate PR to update the lockfile will likely do the same thing anyway.
>

In that case, why not leave it to renovate? That's what I'd suggest, but again, I'm fine with landing this if you like.

**Comment by willdurand** [comment]
> In that case, why not leave it to renovate?

I agree. Thanks!

**Pull request closed without merging**
