### PR TITLE
fix: Button text-shadow and hover in SearchSort

### LINKED ISSUE #2436: Create a Desktop Header (for detail and landing pages)
Create a desktop header for inner/detail and one for landing pages.

### Landing Pages
screenshot 2017-05-25 16 05 20

### Detail Pages
screenshot 2017-05-25 13 43 22

### PR DESCRIPTION
**Pull request by tofumatt**
Closes #2436.

Fixes the search sort to not have a text-shadow after a button refresh.

In the future (as I redo the search page for desktop) the search sort could do with a general CSS cleanup but this fixes the issue for now.

### After
screenshot 2017-06-07 17 23 31

### CODE REVIEW

**Comment by tofumatt** [comment]
I've got to add the same tweak to the next/previous buttons actually. It's gonna be the same CSS... just a sec 😄

**Comment by tofumatt** [comment]
screenshot 2017-06-09 14 51 38

Added a fix for the prev/next links too.

**Comment by muffinresearch** [comment]
I wonder with 3 uses should this be factored out - but np if it's easier to look at this alongside potentially reconsidering the mixin approach.

r+wc

**Comment by tofumatt** [comment]
Yeah they definitely should but I'll overhaul it with the mixin change and likely an update to these styles later in the desktop/photon stuff anyhow... for now I just don't wanna break production 😄

**Pull request merged**
