### PR TITLE
Update loading-page.html

### LINKED ISSUE #3731: Add link: preload for fonts
Add before the CSS in the `<head>`.

```
<link rel="preload" href="https://addons-amo.cdn.mozilla.net/979a13914c3398f40c3114ead422ed41.woff2" as="font" type="font/woff2" crossorigin>
…
```

Kickstarts the font download when the browser parsed the header but has not started parsing the CSS yet.

### PR DESCRIPTION
**Pull request by Shivansh2407**
Fixes #3731 
Add link: preload for fonts #3731

### CODE REVIEW

**Comment by Shivansh2407** [comment]
@codecov-io I have added a line in the file . Please check .

**Comment by muffinresearch** [comment]
This file is only used for development so it's not the right file to change to fix #3731

**Comment by Shivansh2407** [comment]
So which file should I change for fixing this issue.

**Comment by bobsilverberg** [comment]
> So which file should I change for fixing this issue.

I believe the line should be added at https://github.com/mozilla/addons-frontend/blob/master/src/core/components/ServerHtml/index.js#L219, right after the `<link>` for the shortcut icon.  As mentioned in the issue, there may be issues with using `preload` vs. `prefetch`. You can see in the file referenced that we seem to use both for the assets loaded via the `renderPreLinks`.

I'm not sure exactly how you'd test to see which, if either, of these work. I'm also not sure if you can simply hardcode `https://addons-amo.cdn.mozilla.net/979a13914c3398f40c3114ead422ed41.woff2` as suggested in the issue, or if that needs to be calculated in some way.

You can continue with this if you'd like to take those challenges on, but this issue might not be suitable to contributors. We tend to mark those issues with `contrib: welcome`, and you can see the list of those [here](https://github.com/mozilla/addons-frontend/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22contrib%3A+welcome%22).

**Comment by muffinresearch** [comment]
In lieu of updates to this, I'm going to close it out. If you would like to further the patch based on the comments above please feel free to reopen the pr.

**Pull request closed without merging**
