### PR TITLE
Add fy-NL lang to config

### PR DESCRIPTION
**Pull request by tofumatt**
This is why the tests are suddenly failing 😄

### CODE REVIEW

**Comment by muffinresearch** [comment]
Might be nice to build the locale JSON bundle too as part of this so it works on the front-end.

**Comment by muffinresearch** [comment]
`NODE_APP_INSTANCE=disco bin/build-locales` should do it.

**Comment by tofumatt** [comment]
Oh, cheers. Didn’t know about that, I’ll do it and update the PR.

**Comment by muffinresearch** [comment]
r+ thanks!

**Pull request merged**
