### PR TITLE
Removed all calls to getAddonTypeFilter()

### LINKED ISSUE #8256: Remove `getAddonTypeFilter()`
We can remove the `getAddonTypeFilter()` function now that we do not have to support lightweight themes. We only have static themes:

- All calls to `getAddonTypeFilter()` should be changed to `ADDON_TYPE_STATIC_THEME`
- The `config` is often given to this function. In the caller, if we only use the config to call `getAddonTypeFilter`, then we should also remove the config code since that won't be used elsewhere anymore

**For QA:** there should be no obvious regression. We changed code related to the "landing pages" (`/extensions/` and `/themes/` for both Android and FF Desktop). We also touched code related to the "other add-ons by authors".

### PR DESCRIPTION
**Pull request by Shubhamchinda**
Fixes #8256

Removed all the calls to getAddonTypeFilter().

### CODE REVIEW

**Comment by Shubhamchinda** [comment]
@championshuttler Okay! I'll look into it and make the changes soon.
Thanks.

**Comment by Shubhamchinda** [comment]
@willdurand Sorry, I messed up. I'll do it from the start. Any help would be appreciated.
Thanks :)

**Comment by willdurand** [comment]
@willdurand I cleaned your branch :)

**Comment by Shubhamchinda** [comment]
Hey @willdurand, can you please help me here.

**Comment by willdurand** [comment]
> Hey @willdurand, can you please help me here.

Looks like lots of tests have been broken 😞 I suggest you recreate your patch but you only make a few changes and run `yarn test` all the time to make sure you see what's breaking. That will be easier to fix the test cases.

**Comment by Shubhamchinda** [comment]
@willdurand 
I was also thinking about recreating the patch, So should I just close this PR and make another when I resolve it?

**Comment by willdurand** [comment]
>  I was also thinking about recreating the patch, So should I just close this PR and make another when I resolve it?

yep

**Pull request closed without merging**
