### PR TITLE
Fix space inconsistency of site notice in mobile view

### LINKED ISSUE #8827: The site notice banner has inconsistent margins on mobile view
This was mentioned in a comment at https://github.com/mozilla/addons-frontend/pull/8797#pullrequestreview-305435576.

> The mobile view has inconsistent margins around the site notice. This might have nothing to do with your patch and since it just affects the site notice, feel free to address it in a follow-up.

<details>
<summary>Screenshot</summary>
Screenshot 2019-10-22 14 51 48
</details>

### PR DESCRIPTION
**Pull request by muskangupta-iitr**
Fixes #8827 

Fixed the inconsistency of spacing in the site notice in mobile view.

Screenshot from 2020-03-20 03-36-47

### CODE REVIEW

**Comment by willdurand** [comment]
@muskangupta-iitr thanks for your work on this issue. Could you please attach a "Before this patch" screenshot? Thanks

**Comment by muskangupta-iitr** [comment]
@willdurand Here is the before patch screenshot:
Screenshot from 2020-03-20 14-22-02

**Comment by muskangupta-iitr** [comment]
@willdurand I am working on it. Let me fix it and update the PR. Thanks

**Comment by muskangupta-iitr** [comment]
@willdurand I fixed it using `:empty` CSS selector. As it only causing problem when no elements are present in `AppBanner`class.

**Comment by muskangupta-iitr** [comment]
@willdurand Please review!

**Comment by willdurand** [comment]
> @willdurand I fixed it using `:empty` CSS selector. As it is only causing problem when no elements are present in `AppBanner`class.

mmh I see. So I see that it works but I am not sure if we should be using this `:empty` pseudo selector..

**Comment by muskangupta-iitr** [comment]
> > @willdurand I fixed it using `:empty` CSS selector. As it is only causing problem when no elements are present in `AppBanner`class.
> 
> mmh I see. So I see that it works but I am not sure if we should be using this `:empty` pseudo selector..
@willdurand 
So without empty classes any suggestions ?
Is there any problem with pseudo selector ?

**Comment by willdurand** [comment]
@bobsilverberg what do you think? My gut feeling tells me that we might find a different fix for this but... maybe `:empty` is fine.

**Comment by bobsilverberg** [comment]
> @bobsilverberg what do you think? My gut feeling tells me that we might find a different fix for this but... maybe `:empty` is fine.

`:empty` seems like a reasonable solution, and it seems to work in this case. I think it's fine.

**Comment by muskangupta-iitr** [comment]
@willdurand It's working in my PC. I used `:empty` selector only because it is only causing problem when `AppBanner` have no child. Without `:empty` selector I tried but doesn't find a good solution. Any solution you recommend me to try out?

**Comment by willdurand** [comment]
Yeah, did you look at the link I provided above? There are screenshots attached too, with the expected result. With this patch, I am not seeing any major difference unfortunately.

The link I mentioned is: https://github.com/mozilla/addons-frontend/pull/8928

**Comment by muskangupta-iitr** [comment]
@willdurand I gone through the link you provided and found the final result which needs to be done. With this patch, i getting that result. Let me share with you some of the screenshots with/without applying this patch:

### Without this patch:

#### With site notice:

Screenshot from 2020-03-25 19-48-27

#### Without site notice:

Screenshot from 2020-03-25 19-54-42

### With this patch:

#### With site notice:

Screenshot from 2020-03-25 19-49-42

#### Without site notice:

Screenshot from 2020-03-25 19-49-56

**Comment by willdurand** [comment]
Well, maybe I had some problems with my local setup but that's not what I had. Also, please make sure to test with 2 notices (the site notice and the Android compat one which can be displayed when browsing http://localhost:3000/en-US/android/extensions/ I believe).

**Comment by muskangupta-iitr** [comment]
> Well, maybe I had some problems with my local setup but that's not what I had. Also, please make sure to test with 2 notices (the site notice and the Android compat one which can be displayed when browsing http://localhost:3000/en-US/android/extensions/ I believe).

Ohk @willdurand!


### Without this patch:

Screenshot from 2020-03-25 21-29-41

### With this patch:

#### With site notice:

Screenshot from 2020-03-25 21-30-21

#### Without site notice:

Screenshot from 2020-03-25 21-31-03

#### Without any notice:

Screenshot from 2020-03-25 21-30-44

@willdurand Done :+1:

**Comment by willdurand** [comment]
Interesting...

@bobsilverberg I know Kumar suggested an alternative in the past but this seems okay according to the screenshots. Yet, I haven't been able to reproduce locally. Would you have time to look into this patch? Thanks!

**Comment by bobsilverberg** [comment]
> Interesting...
> 
> @bobsilverberg I know Kumar suggested an alternative in the past but this seems okay according to the screenshots. Yet, I haven't been able to reproduce locally. Would you have time to look into this patch? Thanks!

What have you not been able to reproduce? The original issue, or the fix with this patch? I tested this the last time you asked and it looked like the patch fixes the issue.

**Comment by willdurand** [comment]
> What have you not been able to reproduce? The original issue, or the fix with this patch? I tested this the last time you asked and it looked like the patch fixes the issue.

This patch, specifically. I don't see obvious differences.

**Comment by bobsilverberg** [comment]
> > What have you not been able to reproduce? The original issue, or the fix with this patch? I tested this the last time you asked and it looked like the patch fixes the issue.
> 
> This patch, specifically. I don't see obvious differences.

I am seeing a difference with this patch.

Without the patch:

Screenshot 2020-03-26 08 50 41

Note that the margins above and below the site notice are smaller than those between other cards.

With the patch:

Screenshot 2020-03-26 08 51 28

Note that the margins above and below the site notice are the same as those between other cards.

Are you not seeing this difference locally, @willdurand?
 
What is interesting, however, is that the original issue was about the margins being inconsistent *around* the site notice. Look at the screenshot from the original issue:

Screenshot 2019-10-22 14 51 48

The margin above the site notice is smaller than the margin below the site notice. I believe that was the reason the original issue was filed, but that doesn't seem to be reproducible anymore. So I don't think the original issue even exists anymore, but it does seem like the current site has margins that are too small.

**Comment by bobsilverberg** [comment]
I was incorrect in what I wrote in my comment, above. The original issue is reproducible if the WrongPlatformWarning is displayed. I deleted my comments to the contrary.

**Comment by willdurand** [comment]
> Are you not seeing this difference locally, @willdurand?

I just retried and now it does work.. Thanks for confirming.

**Pull request merged**
