### PR TITLE
changing the order of calls of unloadCollectionBySlug & pushLocation

### LINKED ISSUE #5708: My collections page is trying to access a deleted collection right after the collection has been deleted
STR:

1. Log in to AMO
2. Go to View My collection
3. Select one of your collections to view its details page
4. Open the web console and go to the Network tab
5. Click on Delete this collection
6. Observe the API calls made in the Network tab

Actual result:
There is a request sent to get the details of the collection that has just been deleted, resulting in a 404 response

Expected result:
My collections page should not try to access details for a collection that has just been deleted

Notes:
- there are no visible errors on My collections listing page
- these are the two endpoints accessed: 
1. `https://addons-dev.allizom.org/api/v3/accounts/account/<user>/collections/<coll_slug>/?lang=en-US&wrap_outgoing_links=true`
2. `https://addons-dev.allizom.org/api/v3/accounts/account/<user>/collections/<coll_slug>/addons/?page=1&sort=-added&lang=en-US&wrap_outgoing_links=true`
- reproduced on all AMO servers with FF61, Win10x64

404 req my coll

### PR DESCRIPTION
**Pull request by championshuttler**
Fixes #5708 

Before: 
screenshot from 2018-08-03 12-53-17

After:
screenshot from 2018-08-03 12-54-26

### CODE REVIEW

**Comment by championshuttler** [comment]
Why the `security/synk` is failing? :disappointed:

**Comment by willdurand** [comment]
> Why the security/synk is failing? 😞

This is probably unrelated to your changes. Could you please rebase your PR?

**Comment by championshuttler** [comment]
Hey @willdurand done , sorry for the delay , was travelling :disappointed:

**Comment by championshuttler** [comment]
Hi @Willdurand , is there anything pending here? 😉

**Comment by willdurand** [comment]
@championshuttler heh sorry, I think tests need to be updated:

```
diff --git a/tests/unit/amo/sagas/test_collections.js b/tests/unit/amo/sagas/test_collections.js
index 57c178a..f72c976 100644
--- a/tests/unit/amo/sagas/test_collections.js
+++ b/tests/unit/amo/sagas/test_collections.js
@@ -822,17 +822,18 @@ describe(__filename, () => {
 
       _deleteCollection(params);
 
-      const expectedUnloadAction = unloadCollectionBySlug(params.slug);
-
-      const unloadAction = await sagaTester.waitFor(expectedUnloadAction.type);
-      expect(unloadAction).toEqual(expectedUnloadAction);
-
       const expectedPushAction = pushLocation(
         `/${lang}/${clientApp}/collections/`,
       );
 
       const pushAction = await sagaTester.waitFor(expectedPushAction.type);
       expect(pushAction).toEqual(expectedPushAction);
+
+      const expectedUnloadAction = unloadCollectionBySlug(params.slug);
+
+      const unloadAction = await sagaTester.waitFor(expectedUnloadAction.type);
+      expect(unloadAction).toEqual(expectedUnloadAction);
+
       mockApi.verify();
     });
```

**Comment by championshuttler** [comment]
Hey @willdurand done;), would you mind if you merge it tomorrow because I am thinking to make a small tutorial kind of video to how to solve the bugs for amo frontend for my local Mozilla community. We might have some new contributors onboard after that.

Thanks

**Comment by willdurand** [comment]
> Hey @willdurand done;), would you mind if you merge it tomorrow because I am thinking to make a small tutorial kind of video to how to solve the bugs for amo frontend for my local Mozilla community. We might have some new contributors onboard after that.

@championshuttler when exactly do you want to get it merged?

**Pull request merged**
