### PR TITLE
Replace puzzle icon with Firefox in the header

### PR DESCRIPTION
**Pull request by kumar303**
Fixes https://github.com/mozilla/addons-frontend/issues/3763

Screenshots:

**XL**:

screenshot 2017-11-03 14 37 42

**L**:

screenshot 2017-11-03 14 38 35

**M**:

screenshot 2017-11-03 14 39 01

**S**:

screenshot 2017-11-03 14 39 29

Right to left example:

screenshot 2017-11-03 14 40 26

### CODE REVIEW

**Comment by willdurand** [comment]
I noticed this in the mockup from the issue but it is even more visible on your screenshots 1, 3 and 4. Everything looks misaligned 😕

The menu is floating without really being aligned vertically. Maybe we should align it with the search bar (cf. Screenshots 1 and 3), what do you think?

**Comment by muffinresearch** [comment]
@kumar303 I think this will require some tweaking and maybe some refactoring of the header to make it work a bit better since the bigger icon does seem to change everything as Will pointed out. 

Re: the wordmark idea, currently the heading string is being translated. I wonder if "Firefox Add-ons" is seen more as branding then would we still need the translations for it? Test Pilot doesn't appear to have that issue since it doesn't look like they have localisations. 

If it was appropriate to use a wordmark (including "Add-ons"), that might simplify some things and we wouldn't have to make so many considerations in the layout for long translations which is why things work the way they do currently. Of course RTL would also need consideration in any case.

**Comment by muffinresearch** [comment]
I spoke to @jvillalobos about this today and we concluded that we could use an SVG wordmark for the entire logo e.g. `[FFLOGO] Firefox Add-ons` this can then have localized alternate text but keeps a visual consistency for the whole site. 

This should mean the grid can be simplified and it should make the whole thing a bit easier from a responsive perspective.

I'll see about getting an asset to us use for this ASAP.

**Comment by muffinresearch** [comment]
Here's a combined wordmark svg based on @pwalm's spec:

Example screenshot in InkScape:
firefox-addons-logo-horizontal-lockup-1_svg_-_inkscape

Svg in zip file:
[firefox-addons-min.svg.zip](https://github.com/mozilla/addons-frontend/files/1441909/firefox-addons-min.svg.zip)

**Comment by kumar303** [comment]
The wordmark looks way better. I updated the screenshots -- this is ready for another look. 

Some notes:
* I sized up the logo to 48px in the large/medium/small screens instead of 32px like the puzzle icon. I think the text looks better like this because the new logo has a bigger size in proportion to the text.
* I noticed that the distance between menu items is 24px not 36px like the Sketch spec for the header said but I kept it as is
* @willdurand I'm not sure if I fully addressed your comments about aligning things to the search bar. I tried to follow the current site's layout for now instead of improve on it -- maybe we need a follow-up issue?

**Comment by kumar303** [comment]
The build will be fixed after https://github.com/mozilla/addons-frontend/pull/3777

**Comment by willdurand** [comment]
> @willdurand I'm not sure if I fully addressed your comments about aligning things to the search bar. I tried to follow the current site's layout for now instead of improve on it -- maybe we need a follow-up issue?

Yes, we should. It was not really aligned before but the new bigger icon makes it obvious that it needs some love.

I noticed one issue on "focus", I think the color should be `$white`:

screen shot 2017-11-03 at 21 51 13

**Comment by kumar303** [comment]
> Yes, we should. It was not really aligned before but the new bigger icon makes it obvious that it needs some love.

Are you talking about how the menu doesn't line up horizontally with the search bar in the large and medium screenshots up above?

> I noticed one issue on "focus", I think the color should be $white

Oops, I removed that because I didn't think we needed it. I put it back :)

**Comment by willdurand** [comment]
> Are you talking about how the menu doesn't line up horizontally with the search bar in the large and medium screenshots up above?

yes!

**Pull request merged**
