### PR TITLE
Tests added for PR #9973 Changed older versions button to links

### LINKED ISSUE #9811: Show download links instead of install buttons in all versions page
### Describe the problem and steps to reproduce it:

1. Install NoScript (possibly an older version).
2. Visit https://addons.mozilla.org/en-US/firefox/addon/noscript/versions/ and/or
  https://addons.mozilla.org/en-US/firefox/addon/noscript/
3. Try to install an older version, or at least find a "Download file" link (from #4910).

### What happened?
I am not able to install or download an older version. All buttons have changed to "Remove".

I cannot upgrade to the latest version via the addon listing because there is only a "Remove" button.

### What did you expect to happen?
It should be possible to install or download an older version.

### Anything else we should know?

Actually, it is possible to download, by right-clicking on the button and opening it in a new tab/window, because the button is actually a link. This is however not obvious and not a great user experience.

### PR DESCRIPTION
**Pull request by smitbarmase**
Fixes #9811 

Added tests for 3 files changed by @sarthakkundra for PR #9973

### CODE REVIEW

**Comment by smitbarmase** [comment]
@bobsilverberg I have added all the required tests. Can you please review this?

**Comment by bobsilverberg** [comment]
Thanks for taking this on @smitbarmase, and my apologies for the delay. Unfortunately this patch has issues because it is built against an old version of the code, so testing locally generates errors. Would you be able to rebase it on top of the latest code from `master`?

**Comment by smitbarmase** [comment]
@bobsilverberg I rebased my branch `test-download-links` with `upstream/master`. This was the first time I rebased. Is this how it is supposed to work? Let me know if need any changes from my side :)

**Comment by bobsilverberg** [comment]
@smitbarmase It didn't exactly work because it should not have added all of those extra commits to your PR. Let me see if I can clean it up for you.

**Pull request closed without merging**
