### PR TITLE
Remove cookie anchor in a footer link

### LINKED ISSUE #8934: Display of "Cookies" link jumps to page footer on Android
### STR:
1. From any AMO page, scroll to the page footer.
2. Click on the "Cookies" link.

### Expected result:
The "Websites, Communications & Cookies Privacy Notice" page opens on the cookies page information.
### Actual result:
The "Websites, Communications & Cookies Privacy Notice" page opens on the page footer.

### Notes:
Reproduced on all AMO servers with an Android 8.0.0 small device.
 On Win10 the "Cookies" link displays the page as intended. (2nd gif)

videotogif_2019 11 14_16 57 32

### PR DESCRIPTION
**Pull request by stringtheory1234**
Fixes #8934

Replace this sentence with a description of how your patch fixes the issue.

### CODE REVIEW

**Comment by stringtheory1234** [comment]
what does it mean by this codecov report??

**Comment by willdurand** [comment]
> what does it mean by this codecov report??

Code  coverage is a metric to determine how much code has been executed by the test suite. Codecov is a tool that measures the coverage. When it says that the coverage hasn't change, it means the same amount of code has been executed, even with your changes. In other words, it means you did not introduce new code without tests (this is not entirely accurate but here it is valid).

**Comment by willdurand** [comment]
Thanks for contributing @stringtheory1234! /cc @caitmuenster

**Comment by caitmuenster** [comment]
Thanks so much for the patch, @stringtheory1234! 🎉 Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition). 

Would you be interested in creating an account on mozillians.org? I'd be happy to vouch for you!

**Comment by stringtheory1234** [comment]
@caitmuenster yeah sure!
It would be great if you could vouch for me : https://mozillians.org/en-GB/u/ishitakaul07/

**Comment by caitmuenster** [comment]
@stringtheory1234 You're vouched! ✨

Welcome onboard! We look forward to seeing you around.

**Comment by stringtheory1234** [comment]
Thanks @caitmuenster !!

**Pull request merged**
