### PR TITLE
Limit the max height for review entry form

### LINKED ISSUE #6344: The review entry form expands too much
### Describe the problem and steps to reproduce it:

- Sign in
- Rate an add-on
- Begin writing a review
- Enter a lot of text

### What happened?

The review entry form expands too much

<details>
<summary>Example</summary>

screenshot_2018-09-21 octopar-troose-jagle-new-name add-ons for firefox

</details>

### What did you expect to happen?

After 600 characters, the review form should stop expanding. Scrollbars should appear.

### Anything else we should know?

Take a look at how [`AddonReviewManager`](https://github.com/mozilla/addons-frontend/blob/f71a19331ba96d409ea4d91b0f89a65a383198c9/src/amo/components/AddonReviewManager/index.js) uses [`DismissibleTextForm`](https://github.com/mozilla/addons-frontend/blob/f71a19331ba96d409ea4d91b0f89a65a383198c9/src/ui/components/DismissibleTextForm/index.js).

### PR DESCRIPTION
**Pull request by saranshbarua**
Fixes #6344 .
The following change introduces a scrollbar after a limited number of charachters (600: as suggested in the issue) are entered in the review entry form.

screen shot 2018-10-15 at 1 12 40 am

### CODE REVIEW

**Comment by saranshbarua** [comment]
@kumar303 Please take a look.

**Comment by championshuttler** [comment]
Hi @saranshbarua thanks for the PR, before any mentor review your PR , i think you need take back changes made in `yarn.lock` file as its not related to the issue :) . Let us know if you need any help regarding same :smile:

**Comment by saranshbarua** [comment]
@championshuttler I reverted back to my last change. And now this shows yarn.lock as a conflicting file.

**Comment by championshuttler** [comment]
@saranshbarua i think you need to rebase your PR for that and [here](https://github.com/mozilla/addons-frontend/pull/6622/files) you can see that you still made few changes in `yarn.lock` file

**Pull request closed without merging**
