### PR TITLE
Eslint 4.3

### PR DESCRIPTION
**Pull request by tofumatt**
eslint complained about a LOT of indentation errors here. I ran `eslint --fix`... but I wonder what the diff looks like and if it's what we wanted. Posting here to see the diff.

Closes #2721

### CODE REVIEW

**Comment by muffinresearch** [comment]
I think most of these changes look ok - not sure why the test is showing still in progress it completed already. 

Maybe there's a few cases here where a manual update to the formatting would do things slightly differently.

**Comment by muffinresearch** [comment]
@tofumatt what do you think about removing the space after `async` that one seems a little odd to me.

**Comment by muffinresearch** [comment]
I'll file an issue to fix that in eslint-config-amo.

**Comment by muffinresearch** [comment]
@tofumatt I patched the eslint config so this should allow the space behind the async keyword now.

**Comment by muffinresearch** [comment]
@tofumatt if you can rebase this it should be pretty much good to go...

**Comment by tofumatt** [comment]
Ten four, I’ll take a look after the standup.

**Comment by tofumatt** [comment]
Sorry all for the merge conflicts this'll likely create! 😅

**Comment by willdurand** [comment]
@tofumatt I get these warnings now:

```
can't resolve reference #/definitions/basicConfig from id #
can't resolve reference #/definitions/basicConfigOrBoolean from id #
can't resolve reference #/definitions/basicConfigOrBoolean from id #
```

There is a similar issue on the airbnb preset: https://github.com/airbnb/javascript/issues/1488, which is related to https://github.com/yannickcr/eslint-plugin-react/pull/1292.

Do you see these messages too?

**Comment by tofumatt** [comment]
Yeah, I’ve seen those too but they are apparently okay to ignore. They don’t cause anything to fail and are because of a dependency issue :-/

**Pull request merged**
