### PR TITLE
Tweak disco pane styles

### LINKED ISSUE #899: Adjust text to allow for dev name on blocks
**Theme and extension block**
screen shot 2016-08-09 at 9 45 09 am

screen shot 2016-08-09 at 9 54 22 am

/* header: */
font-family: HelveticaNeue-Bold;
font-size: 14px;
color: #444444;
letter-spacing: 0px;

/* dev name-normal: */
font-family: HelveticaNeue-Light;
font-size: 10px;
color: #6A6A6A;
letter-spacing: 0px;

/* dev name-hover: */
font-family: HelveticaNeue-Light;
font-size: 10px;
color: #0996F8;
letter-spacing: 0px;

/* secondary copy: */
font-family: HelveticaNeue;
font-size: 12px;
color: #444444;
line-height: 14px;

### PR DESCRIPTION
**Pull request by mstriemer**
screenshot 2016-08-13 23 06 06
> Full view

screenshot 2016-08-13 23 06 15
> Hover over link

screenshot 2016-08-13 22 56 44
> Hover over link

Fixes #899.

This depends on the changes in https://github.com/mozilla/addons-server/pull/3270.

### CODE REVIEW

**Comment by mstriemer** [comment]
@pwalm I find these font sizes a little small. It looks like you might have had some other tweaks in mind but I only included the ones from your CSS snippet.

**Comment by muffinresearch** [comment]
> @pwalm I find these font sizes a little small. It looks like you might have had some other tweaks in mind but I only included the ones from your CSS snippet.

I agree, the span also feels a little bit cramped against the main title now it's `display: block` and underneath.

**Comment by muffinresearch** [comment]
r+wc re the changes - but I'd agree on seeing about bumping the text size + whitespace around the span depending on the feedback from UX.

**Comment by muffinresearch** [comment]
One other thing is that the issue linked mentions linking up the authors as well as the add-on. Not sure what that would look like in the sense that the "by" would probably be unlinked if we did that.

**Comment by pwalm** [comment]
screen shot 2016-08-15 at 8 36 31 pm

Hey guys:
- I never properly spec'd out the theme block, sorry about that.
- Gotta keep that extension name/dev name copy small, since we have an extension name that is 64 (!) characters long (and we can't truncate or shorten that copy).
- Bumping up the white space a touch (like 5px) sounds fine.
- The links should only go to the extension/theme detail page in question. Don't link to their dev pages. Too confusing.
- Only link the dev name on the theme block, don't make the theme name a link. Follow the styling on the extension block.

**Comment by mstriemer** [comment]
I added 3px of top padding. 5px seemed a bit much.

screenshot 2016-08-16 10 42 28
screenshot 2016-08-16 10 42 35
screenshot 2016-08-16 10 42 41

**Comment by pwalm** [comment]
Good call, looks nice.

**Comment by mstriemer** [comment]
QA:

This is just a style update. The page should like like pwalm's last screenshot but without the stars/user count or enhanced drop shadow.

There are currently AWS issues which may prevent the server side portion of this working correctly until addons-server can be deployed to stage.

**Comment by mstriemer** [comment]
@pwalm do you want to file another bug for the stars/user count/drop shadow?

**Comment by pwalm** [comment]
@mstriemer Yep, we'll keep that separate.

**Pull request merged**
