### PR TITLE
Remove search locale json files

### LINKED ISSUE #465: Don't load a bundle for english locale
* We don't need a request for en_US since that's the default key value

### PR DESCRIPTION
**Pull request by muffinresearch**
Since there's no current plans to localize the search we don't need the JSON.

* Modifies the dev config to only build the bundles for the current app.
* Fixes the fallbacks to gettext key when locale doesn't exist.
* No JS bundle loaded for en-US locale.

Fixes #465

### CODE REVIEW

**Comment by mstriemer** [comment]
I don't see any errors on the page but this seems to cause the search form to do full page refreshes instead of using XHR.

**Comment by muffinresearch** [comment]
> I don't see any errors on the page but this seems to cause the search form to do full page refreshes instead of using XHR.

Ok I'll take a look tomorrow - I presume it's only in this branch and not in master?

**Comment by mstriemer** [comment]
Yeah, it's still working on master for me.

**Comment by muffinresearch** [comment]
@mstriemer I don't seem to be able to login locally. Is there a way to do the login for local development?

**Comment by mstriemer** [comment]
I think you need to run a local server and start it with `API_HOST=http://olympia.dev npm run dev:search` for login to work or else you get redirected to https://addons-dev.allizom.org after. I still need to add support for -dev redirecting to and accepting localhost.

**Comment by muffinresearch** [comment]
OK, this should be fixed now.

**Comment by mstriemer** [comment]
Works for me now. r+

**Pull request merged**
