### PR TITLE
Storybook upgrade

### LINKED ISSUE #6955: `yarn storybook-build` is broken
### Describe the problem and steps to reproduce it:

1. Run `yarn storybook-build`

### What happened?

```
❯ yarn storybook-build
yarn run v1.12.3
$ better-npm-run storybook-build
running better-npm-run in /Users/williamdurand/projects/mozilla/addons-frontend
Executing script: storybook-build

to be executed: build-storybook -c stories/setup
info @storybook/react v3.4.10
info
info => Loading custom .babelrc
info => Loading custom addons config.
WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
/Users/williamdurand/projects/mozilla/addons-frontend/node_modules/config/lib/config.js:203
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "webpackServerHost" is not defined
    at Config.get (/Users/williamdurand/projects/mozilla/addons-frontend/node_modules/config/lib/config.js:203:11)
    at Object.<anonymous> (/Users/williamdurand/projects/mozilla/addons-frontend/webpack.dev.config.babel.js:32:28)
    at Module._compile (module.js:652:30)
    at loader (/Users/williamdurand/projects/mozilla/addons-frontend/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/williamdurand/projects/mozilla/addons-frontend/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/williamdurand/projects/mozilla/addons-frontend/stories/setup/webpack.config.babel.js:2:1)
    at Module._compile (module.js:652:30)
    at loader (/Users/williamdurand/projects/mozilla/addons-frontend/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/williamdurand/projects/mozilla/addons-frontend/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### What did you expect to happen?

No error.

### Anything else we should know?

The `gh-pages` branch has not been update since October 15, 2018. I suppose that's broken since then. We have no output on Travis CI for this job, so hard to tell...

### PR DESCRIPTION
**Pull request by willdurand**
Fixes #6955 

---

Some commits come from #7009.

~~The build step has been fixed, but the `Badge` component does not list the props anymore...~~ This has been fixed.

### CODE REVIEW

**Comment by willdurand** [comment]
/cc @rebmullin for some help on:

>  the `Badge` component does not list the props anymore...

**Comment by rebmullin** [comment]
> the Badge component does not list the props anymore...

it seems that it has something to do with it being a stateless component. When I converted it to a class (for testing), it worked. I'll have to dig into this more..

**Comment by willdurand** [comment]
> it seems that it has something to do with it being a stateless component. When I converted it to a class (for testing), it worked. I'll have to dig into this more..

Yep, that's correct. I cannot find reliable info on that, though.

**Comment by rebmullin** [comment]
@willdurand, another "hint" is that when you don't use our babel-loader settings, it works. I did something like this originally [here](https://github.com/mozilla/addons-frontend/pull/6571/commits/1029c39cc0b6c4ac234729b84c56f97b4485a5a4#diff-7cbcf263285452231f6c436b60b07c21R28).

I know it's not the ideal way but so far this is the only way I got it working.

**Comment by willdurand** [comment]
> @willdurand, another "hint" is that when you don't use our babel-loader settings, it works. I did something like this originally [here](https://github.com/mozilla/addons-frontend/pull/6571/commits/1029c39cc0b6c4ac234729b84c56f97b4485a5a4#diff-7cbcf263285452231f6c436b60b07c21R28).
> 
> I know it's not the ideal way but so far this is the only way I got it working.

heh, very interesting, thanks!

**Comment by willdurand** [comment]
@rebmullin thanks, everything is fixed now!

**Pull request merged**
