### PR TITLE
Fixes #8934

### LINKED ISSUE #8934: Display of "Cookies" link jumps to page footer on Android
### STR:
1. From any AMO page, scroll to the page footer.
2. Click on the "Cookies" link.

### Expected result:
The "Websites, Communications & Cookies Privacy Notice" page opens on the cookies page information.
### Actual result:
The "Websites, Communications & Cookies Privacy Notice" page opens on the page footer.

### Notes:
Reproduced on all AMO servers with an Android 8.0.0 small device.
 On Win10 the "Cookies" link displays the page as intended. (2nd gif)

videotogif_2019 11 14_16 57 32

### PR DESCRIPTION
**Pull request by stringtheory1234**
Fixes #ISSUE_NUMBER

Replace this sentence with a description of how your patch fixes the issue.

### CODE REVIEW

**Comment by stringtheory1234** [comment]
Screenshot from 2020-01-07 20-42-23

Hi, thanks for your response @willdurand, I am new to open-source! I have a small doubt, here should I just remove #cookies in line 37 ??

**Comment by willdurand** [comment]
> Hi, thanks for your response @willdurand, I am new to open-source! I have a small doubt, here should I just remove #cookies in line 37 ??

I think that would work indeed.

Make sure to install this project locally and run `yarn test` to confirm.

**Comment by stringtheory1234** [comment]
showing Expected <a> to match for prop "href", but it did not,  error. @willdurand 
Screenshot from 2020-01-07 23-23-05

**Comment by willdurand** [comment]
Fixed in https://github.com/mozilla/addons-frontend/pull/9066

**Pull request closed without merging**
