### PR TITLE
Collapse text in long add-on reviews

### LINKED ISSUE #6242: Collapse text in long add-on reviews
### Describe the problem and steps to reproduce it:

- Write a really long add-on review
- As a developer of the same add-on, reply to that review with a really long response

### What happened?

It looks pretty bad on the detail page:

<details>
<summary>Full page screenshot</summary>

screenshot_2018-09-13 sound control add-ons for firefox

</details>

### What did you expect to happen?

The text should be collapsed with a *Read more* link

### Anything else we should know?

This also looks pretty bad on the review listing pages.

We should be able to use [`ShowMoreCard`](https://github.com/mozilla/addons-frontend/blob/f71a19331ba96d409ea4d91b0f89a65a383198c9/src/ui/components/ShowMoreCard/index.js) for this.

### PR DESCRIPTION
**Pull request by Shubhamchinda**
Fixes #6242 

@kumar303 

I made few changes to the existing closed PR, Let me know if this is correct. After that I'll head to the test cases.

Thanks a lot!

### CODE REVIEW

**Comment by Shubhamchinda** [comment]
Thanks a lot @kumar303 for reviewing. I'll look into it and update the PR.

**Comment by jvillalobos** [comment]
@Shubhamchinda Are you still working on this?

**Comment by Shubhamchinda** [comment]
> @Shubhamchinda Are you still working on this?

@jvillalobos Sorry, I was busy in exams! I'll look into it now.

**Comment by willdurand** [comment]
> @jvillalobos Sorry, I was busy in exams! I'll look into it now.

@Shubhamchinda I am going to close this patch now. No worries, if you want to work on it again, that's fine. You can either re-open it or create a new one. If you'd like to work on something else, that's no problem too. Thanks!

**Pull request closed without merging**
