### PR TITLE
adding withRouter to authenticateButton

### LINKED ISSUE #6176: Use withRouter for AuthenticateButton so it gets a location prop
**For QA**: Please check for regressions on the following pages: *TBA*

The `AuthenticateButton` requires a `location` prop which means every component that calls it must pass it a `location`. 

Let's use `withRouter()` instead so that it gets `history.location` automatically. 

This will allow us to remove prop drilling in a few components: `FlagReviewMenu`, `RatingManager`, `CollectionList`, and maybe others.

### PR DESCRIPTION
**Pull request by championshuttler**
Fixes #6176

### CODE REVIEW

**Comment by willdurand** [comment]
> In addition, you should probably look at the `<AuthenticateButton />` in the code, and remove the `location` prop (because it is given by the HOC now)

This will require an update of the flow definitions.

**Comment by willdurand** [comment]
@championshuttler see https://travis-ci.org/mozilla/addons-frontend/jobs/429226996 for the Flow issues.

**Comment by championshuttler** [comment]
Hi @willdurand yeah i saw that previously too , can you help me how to solve it , i tried to check other files as well like `amo/components/TestAddonsByAuthorsCard` that how are we solving it, but did not get any lead :/

**Comment by willdurand** [comment]
@championshuttler that patch was enough to make everything green again:

```diff
diff --git a/src/core/components/AuthenticateButton/index.js b/src/core/components/AuthenticateButton/index.js
index 16e1edf73..8a3047d62 100644
--- a/src/core/components/AuthenticateButton/index.js
+++ b/src/core/components/AuthenticateButton/index.js
@@ -30,7 +30,6 @@ type Props = {|
   className?: string,
   handleLogIn?: HandleLogInFunc,
   handleLogOut?: HandleLogOutFunction,
-  location: ReactRouterLocationType,
   logInText?: string,
   logOutText?: string,
   noIcon?: boolean,
@@ -41,6 +40,7 @@ type InternalProps = {|
   api: ApiState,
   handleLogIn: HandleLogInFunc,
   i18n: I18nType,
+  location: ReactRouterLocationType,
   siteUser: UserType | null,
 |};
 
diff --git a/tests/unit/core/components/TestAuthenticateButton.js b/tests/unit/core/components/TestAuthenticateButton.js
index de06368cf..d219299c6 100644
--- a/tests/unit/core/components/TestAuthenticateButton.js
+++ b/tests/unit/core/components/TestAuthenticateButton.js
@@ -24,7 +24,7 @@ import {
 import Icon from 'ui/components/Icon';
 
 describe(__filename, () => {
-  function render(customProps = {}) {
+  function render({ location = createFakeLocation(), ...customProps } = {}) {
     const { store } = dispatchSignInActions();
     const props = {
       handleLogOut: sinon.stub(),
@@ -148,7 +148,7 @@ describe(__filename, () => {
       <AuthenticateButton store={store} {...allProps} />,
       AuthenticateButtonBase,
       {
-        shallowOptions: createContextWithFakeRouter({ location }),
+        shallowOptions: createContextWithFakeRouter(),
       },
     );
```

I am going to update your branch (add the patch above + rebase) if you don't mind.

**Comment by championshuttler** [comment]
Hi @willdurand thanks a lot for the help and doing that :heart:

**Pull request merged**
