### PR TITLE
Is linting working?

### PR DESCRIPTION
**Pull request by mstriemer**
I don't think linting is working right on Travis

### CODE REVIEW

**Comment by muffinresearch** [comment]
Damn, I forgot that travis was split out and doesn't run `npm test`.

I deliberately made lint complete for all tasks because that's more useful in local dev, and had test run things individually.

**Comment by muffinresearch** [comment]
Seems odd that it's still not failing in travis.

**Comment by muffinresearch** [comment]
Just tried another test and it failed as expected: https://github.com/mozilla/addons-frontend/pull/713

**Comment by muffinresearch** [comment]
Landed your patch 4877ca7 and retested #713 - it failed again so I think this is OK.

**Comment by muffinresearch** [comment]
Thanks for catching this!

**Comment by mstriemer** [comment]
Travis was having some issues yesterday so I'm guessing I pushed the extra commit too soon. Thanks for testing it properly.

**Pull request closed without merging**
