### PR TITLE
Allow search results to load without add-on data

### PR DESCRIPTION
**Pull request by kumar303**
Fixes https://github.com/mozilla/addons-frontend/issues/2742

This patch doesn't apply it anywhere but here's an example of what's possible:

search-results-loading mov

### CODE REVIEW

**Comment by kumar303** [comment]
@tofumatt I figured you might also need this for search data so I pulled it out into a separate patch.

**Comment by kumar303** [comment]
To test it locally you'd have to change some code like `<SearchResult addon={addon} />` to `<SearchResult addon={null} />`.

**Comment by tofumatt** [comment]
Omg, awesome!

**Comment by kumar303** [comment]
Should the margin only be applied for the loading case? Or for all cases?

**Comment by kumar303** [comment]
Oh wait, nevermind, you have `.LoadingText` in there. I see.

**Comment by kumar303** [comment]
Yeah, that looks better. Let me know what you think:

screenshot 2017-07-11 17 19 14

**Comment by tofumatt** [comment]
Yeah, when the actual content is there the right margins are applied, because there's a header tag.

**Comment by tofumatt** [comment]
That's great 👍

**Pull request merged**
