### PR TITLE
chore(package): update react-hot-loader to version 3.1.1

### PR DESCRIPTION
**Pull request by willdurand**
Closes #3434

### CODE REVIEW

**Comment by willdurand** [comment]
So HMR still works for me with this PR. We should definitely switch to 3.x, I don't think 1.x will ever receive fixes.

**Comment by kumar303** [comment]
I'm kinda nervous since I don't want anything to break our dev flow before we ship. If you tested it I guess it's fine. We could always revert it.

**Comment by willdurand** [comment]
@tofumatt have you tried this one? 🙏

**Comment by tofumatt** [comment]
I’ve not but I can give it a quick try now. Is there a big benefit to the upgrade? :-)

**Comment by willdurand** [comment]
> Is there a big benefit to the upgrade?

One more PR merged 😋  (and also improvements like better SSR support and reloads, apparently)

We can wait though.

**Comment by tofumatt** [comment]
Fair enough :-) I’ll give it a quick go.

**Comment by kumar303** [comment]
Go for it. It can't possibly break action reloading since that's already broken 😞  https://github.com/mozilla/addons-frontend/issues/1096

**Pull request merged**
