### PR TITLE
Always send an STS header on secure requests

### LINKED ISSUE #716: Add HSTS header via helmet
We should be sending a STS header via the node apps.

### PR DESCRIPTION
**Pull request by muffinresearch**
Fixes #716

### CODE REVIEW

**Comment by mstriemer** [comment]
Can you add a server test that checks that it is set?

r+wc

**Comment by muffinresearch** [comment]
> Can you add a server test that checks that it is set?

Not easily, I wanted to but the only real way to do that would be to force the header being set for a non-secure request or somehow fake `req.secure`. The latter is probably preferable but I'm not sure how to do that in context of supertest. Apparently sending this header for non-http requests is not recommended in case a bad client fails to ignore it so using force is not a good idea.

**Comment by muffinresearch** [comment]
Actually I have an idea...

**Comment by muffinresearch** [comment]
Nope - I can't see a way to do this sanely. Going to merge as is and do a manual test.

**Pull request merged**
