### PR TITLE
Stop decoding HTML entities for collection descriptions

### LINKED ISSUE #10179: Remove dependency on html-entities
We use the `html-entities` library to fix #4375 but this is a rather big dependency (in terms of size). 

I am wondering (1) if we can find a smaller replacement and (2) why this is actually needed (it does not seem to be a problem for other user contents like user descriptions).

### PR DESCRIPTION
**Pull request by diox**
Fixes #10179 (was unblocked by https://github.com/mozilla/addons-server/issues/7648)

### CODE REVIEW

**Review by bobsilverberg — COMMENTED** [review]
This looks good, but I'm not entirely sure what we are trying to accomplish with HTML in collection descriptions. A user is allowed to include HTML in the description when creating it, and this code will output the HTML as text. For example, if my description is `<b>Apples</b> & Oranges`, then what I see displayed is exactly that, i.e., `<b>Apples</b> & Oranges`. Is that what we want, or do we want the HTML to be interpreted so the word "Apples" is in bold (i.e., "<b>Apples</b> & Oranges")? If we do not want to interpret the HTML, and I'm not suggesting we do, then why are we even bothering to allow it at all? Why not strip out all HTML from the description when it is saved on the server? On the other hand, maybe we do want to allow certain tags (e.g., `<b>`) to be interpreted, in which case we can do that, but we need to bring back `sanitizeHTML` and `dangerouslySetInnerHTML`.

**Comment by diox** [comment]
We don't want any HTML, it's just pure text (always has been). We could strip it, but we give no indication that HTML would be supported, so users shouldn't even try adding any, so IMHO it doesn't matter ?

**Comment by diox** [comment]
(This is different from Add-on descriptions, which are generally much longer, and can contain some HTML, and in that case we do attempt to clean it on the server and on the frontend as well)

**Comment by bobsilverberg** [comment]
> We don't want any HTML, it's just pure text (always has been, the fact that we returned some HTML entities was a bug, since fixed). We could strip it, but we give no indication that HTML would be supported, so users shouldn't even try adding any, so IMHO it doesn't matter and just escaping it (what this patch does) is enough ? People will get exactly what they enter (minus URLs that are stripped/forbidden).

We already have code on the server that strips URLs, which is why it seemed to me to make sense to simply add to that and strip all HTML. I suppose, as you say, it doesn't make much difference. The user will see exactly what they enter, and they can always edit it to remove those tags they might have though would "work".

**Review by bobsilverberg — APPROVED** [review]
Based on the discussion in the comments I think this is fine and doesn't need any changes to land. Thanks for taking this on @diox!

**Pull request merged**
