### PR TITLE
Remove code-splitting feature

### PR DESCRIPTION
**Pull request by willdurand**
Fixes https://github.com/mozilla/addons-frontend/issues/10085

---

Given the current state of the two techniques we used for code-splitting (the
loading part), we think it's best to not rely on code-splitting for the static
pages. This patch removes that feature.

I have the feeling that this patch will also "fix" the "chunk errors" we get
in Sentry and we shouldn't break the site because of the `@loadable` libs
anymore :p

### CODE REVIEW

**Review by diox — APPROVED** [review]
At first I was thinking this was a bit going against our goals of improving perf, but the difference in bundle size is fairly small since we never used it for anything else than these 2 pages, so the complexity is probably not worth it, yeah.

**Comment by willdurand** [comment]
> At first I was thinking this was a bit going against our goals of improving perf, but the difference in bundle size is fairly small since we never used it for anything else than these 2 pages, so the complexity is probably not worth it, yeah.

I am actually thinking that it could be better because we'll get rid of the early `preload` requests.

**Comment by diox** [comment]
Yes, but that's cheating because we could get rid of the `preload` requests without removing the code splitting :) But the benefits aren't worth it right now, so I agree with this change.

**Comment by willdurand** [comment]
> Yes, but that's cheating because we could get rid of the `preload` requests without removing the code splitting :) But the benefits aren't worth it right now, so I agree with this change.

I guess we can still revisit code splitting but I don't really see how to make it work in a nice way with the poor `prefetch` support, unless we implement our own prefetch technique.

**Pull request merged**
