### PR TITLE
Clean up 404 routes that we don't need anymore

### PR DESCRIPTION
**Pull request by kumar303**
Fixes https://github.com/mozilla/addons-frontend/issues/2088

### CODE REVIEW

**Comment by kumar303** [comment]
@muffinresearch re: https://github.com/mozilla/addons-frontend/issues/2082 ...

> I'll add comments to the routes to make it clear that ops need to be told when new routes are added.

Did that comment ever get added? Should I add it?

**Comment by muffinresearch** [comment]
> Did that comment ever get added? Should I add it?

Oops, I think that slipped through the net. Good catch - please do.

**Comment by muffinresearch** [comment]
Since it doesn't matter leaving these, would it be worth folding this into the react-router upgrade to avoid having any weird falling-through locally?

**Comment by kumar303** [comment]
> would it be worth folding this into the react-router upgrade to avoid having any weird falling-through locally?

I think it's ok to do the two patches independently. The lack of 404 routes will cause a 500 locally which isn't really any more or less helpful than a 404.

**Pull request merged**
