### PR TITLE
Stop using .development() on server (fix #1235)

### LINKED ISSUE #1235: Don't use `development` method on webpackIsomorphicToolsPlugin
```
[webpack-isomorphic-tools] [error] `.development()` method is now deprecated
(for server-side instance only, not for webpack plugin instance) and has no effect.
Set up a proper `process.env.NODE_ENV` variable instead.
```

### PR DESCRIPTION
**Pull request by tofumatt**
This was bugging me so I stopped it.

Apparently this didn't do anything anymore, which does make me ask: what were we relying on it to do and will it break anything in development?

But everything seems fine so I submit this for review.

### CODE REVIEW

**Comment by muffinresearch** [comment]
> Apparently this didn't do anything anymore, which does make me ask: what were we relying on it to do and will it break anything in development?

From  the docs:

> What does .development() method do? It enables development mode. In short, when in development mode, it disables asset caching (and enables asset hot reload), and optionally runs its own "dev server" utility (see port configuration setting). Call it in development webpack build configuration, and, conversely, don't call it in production webpack build configuration.

We run our own dev server, but does this break hot-reloads?

**Comment by tofumatt** [comment]
So there is `.development()` mode in several things and the place I removed it from it was a no-op (in the future it will be removed). I found the docs/messages about that a bit unclear as well.

Again, as it doesn't do anything now it shouldn't break stuff, but I'll check right now to make sure 😊

**Comment by tofumatt** [comment]
Just checked and hot reload still works:

oct-17-2016 15-18-36

**Comment by muffinresearch** [comment]
lgtm r+

**Pull request merged**
