### PR TITLE
Respect Do Not Track

### PR DESCRIPTION
**Pull request by MaxLeiter**
Ref: https://github.com/mozilla/addons-frontend/issues/2785

### CODE REVIEW

**Comment by ianb** [comment]
Typically Mozilla properties use this DNT function: https://github.com/schalkneethling/dnt-helper/blob/master/js/dnt-helper.js

(Mostly it's that IE defaulted it on, so we don't believe that represents user intent on that browser)

**Comment by MaxLeiter** [comment]
This page is only accessible from Firefox. No need for additional bloat.

**Comment by MaxLeiter** [comment]
Good idea, @tofumatt. Will do

**Comment by MaxLeiter** [comment]
Not really in state, but pretty simple solution. I don't have time to dig around the codebase and figure out a more complex solution.

**Comment by kumar303** [comment]
Google Analytics (in the way [Mozilla has legally contracted Google to operate it](https://bugzilla.mozilla.org/show_bug.cgi?id=697436#c14)) does not count as the T in DNT [as defined by the EFF](https://www.eff.org/deeplinks/2011/02/what-does-track-do-not-track-mean) so I'm not sure this is the right thing to do.

**Comment by tofumatt** [comment]
Yeah... I threw out the idea to use DNT as a way to not load GA but it seems the Tracking Protection pref is the more appropriate thing to use.

That will require more work but I'd say Mozilla's position is GA is not to be blocked by DNT. I was just throwing out ideas, seems my DNT one was wrong.

**Comment by tofumatt** [comment]
So in fact I was wrong and we _should not_ be using GA if DNT is on. I'll close this as I think the AMO team will investigate this and handle it, but thanks a lot for your quick patch @MaxLeiter!

**Pull request closed without merging**
