### PR TITLE
Update links in README.md

### LINKED ISSUE #9827: Fix URL redirection in README.md file
### Describe the problem and steps to reproduce it:
Existing URL redirection in weblinks in README.md.

### What happened?
Clicking on links in README.md leads to URL redirection.

### What did you expect to happen?
No URL redirection.

### PR DESCRIPTION
**Pull request by suriyaa**
Fixes #9827  
@willdurand @bobsilverberg Removed URL redirection in README.md.

### CODE REVIEW

**Comment by bobsilverberg** [comment]
@suriyaa Thanks for the patch. We should have an associated issue filed though. There should never be a PR without a matching issue.

**Comment by suriyaa** [comment]
@bobsilverberg #9827

**Review by bobsilverberg — APPROVED** [review]
Looks good, thanks for the patch @suriyaa

**Comment by caitmuenster** [comment]
Thank you so much, @suriyaa! 🎉 We've added your contribution to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition). 

Welcome onboard! We look forward to seeing you around.

**Pull request merged**
