### PR TITLE
Avoid generating a <p> inside another <p> in addons versions notice

### LINKED ISSUE #10605: Content "jumps" on add-ons versions pages using a Notice after loading
STR:
- Load https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/
- Observe the size of the yellow notice "Be careful with old versions"

Expected results:
- It shouldn't change

Actual results:
- It changes when JavaScript is executed (you can load the page with and without JavaScript enabled to see the difference more clearly)

This seems to be caused by the fact that we put paragraphs inside paragraphs. In the original HTML, before JavaScript is executed, we see:
```html
<div class="Notice-content"><p class="Notice-text"><p class="AddonVersions-warning-text">Be careful with old versions! ...
```
In the generated DOM, elements are shuffled around to fix this, ending up with:
```
- <div class="Notice-content">
  - <p class="Notice-text"></p>
  - <p class="AddonVersions-warning-text">Be careful with old versions! ... </p>
  </div>
```

But React doesn't behave the same way, and happily lets us put a `<p>` inside a `<p>`, so after it's done rendering it transforms the DOM back to something closer to our original intent:
```
- <div class="Notice-content">
  - <p class="Notice-text">
    - <p class="AddonVersions-warning-text">Be careful with old versions! ... </p>
    </p>
  </div>
```

This is bad because it causes a subtle layout change, which forces the LCP to be computed again (making our score worse than it should be for this page). This likely is the cause behind https://github.com/mozilla/addons-frontend/issues/10446 (and I suspect other pages have similar, less visible issues)

### PR DESCRIPTION
**Pull request by diox**
Fixes #10605

### CODE REVIEW

**Comment by diox** [comment]
Not sure what's up with circle CI and the `dennis-lint` job... tried to restart it multiple times, but it didn't work

**Review by bobsilverberg — APPROVED** [review]
Looks good, thanks for digging in and taking care of this @diox!

Do you think we should look into putting something in place that can validate the html we generate to make sure this isn't happening elsewhere?

**Comment by diox** [comment]
I'll file a follow-up, but FWIW I looked at a few other pages and didn't find anything of concern.

**Comment by diox** [comment]
https://github.com/mozilla/addons-frontend/issues/10608 for the follow-up

**Pull request merged**
