### PR TITLE
Move the InstallWarning above the install button

### LINKED ISSUE #11042: Move the InstallWarning above the install button
The `InstallWarning` currently appears below the install button and add-on description:

Screen Shot 2021-12-01 at 12 46 59 PM

To make it more prominent, it should be moved above the install button.

### PR DESCRIPTION
**Pull request by wagnerand**
Fixes #11042.

**Please review this PR with care, I don't have much experience with the frontend.**

# Listing page

## Before
listing-before

## After
listing-after

# Versions page

## Before
version-before

## After
version-after

### CODE REVIEW

**Comment by bobsilverberg** [comment]
Thanks for taking this on @wagnerand! I see Andrew is tagged to review but I will take a look as well. Before I do, there are a few things you should check on your end, if you haven't already done that: 
1. For any change like this, it's important to check its effect at different screen sizes. We have breakpoints at 500px, 720px, 900px and 1150px, so I make sure to test with a screen size that triggers each of those breakpoints. If you want to be really nice you can include screenshots of each one.
2. Please also check with an ltr language.
3. Please also check with an add-on that has a longer description, as that will push everything down further and we want to make sure that it still looks ok.

You don't necessarily need to include screenshots of every combination of 1, 2, and 3, above, but please check them all locally. In case you aren't aware of it, using Firefox's Responsive Design Mode is a really good and easy way to check different screen sizes.

**Comment by wagnerand** [comment]
@bobsilverberg Thank you for the guidance.

For (1), I tested different resolutions by resizing the browser window. Would that work as well?

**Comment by bobsilverberg** [comment]
> @bobsilverberg Thank you for the guidance.
> 
> For (1), I tested different resolutions by resizing the browser window. Would that work as well?

Sure, that works. I just find the Responsive Design Mode to be easier because a) you can specify an exact screen size, and b) it doesn't make your whole browser window smaller, it just reduces the size of the Firefox window in the current tab.

**Comment by wagnerand** [comment]
Ok, I checked both the listing page and the versions page using a LTR and RTL locale for each of the mentioned sizes.

**Review by bobsilverberg — APPROVED** [review]

**Pull request merged**
