### PR TITLE
Add husky and lint-staged to manage a pre-commit hook

### LINKED ISSUE #9939: Use husky and lint-staged to implement a pre-commit hook
[`husky`](https://www.npmjs.com/package/husky) and [`lint-staged`](https://www.npmjs.com/package/lint-staged) can be used in combination to manage a pre-commit hook which will work for anyone who installs the site locally. We can automatically run `prettier`, `eslint`, `stylelint`, and `flow` on every commit, which will help avoid linting errors in commits, and will help users who do not have `prettier` configured to run automatically in their IDE.

Note that the `eslint` step can take a few seconds when there are a large number of files being added to a commit. The time it takes is proportional to the number of files being checked, but I feel like it's worth waiting a few seconds every now and then to have these automatic checks in place.

If we decide this works well, we can add it to addons-code-manager and addons-server as well.

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #9939

### CODE REVIEW

**Comment by willdurand** [comment]
Looks good, thanks. I have a few questions 

Can't we use flow on staged files only? (I don't remember). Also, how could we disable the pre-commit? And I think having some information about the pre-commit in the README.

**Comment by bobsilverberg** [comment]
> Looks good, thanks. I have a few questions
> 
> Can't we use flow on staged files only? (I don't remember). Also, how could we disable the pre-commit? And I think having some information about the pre-commit in the README.

Thanks @willdurand. We can use flow on staged files only, via `lint-staged`, but it's actually much slower than just running flow on the entire code base, which is why I decided to do the latter. I agree we should add something to the README about this. I'll add that in a new commit.

**Comment by bobsilverberg** [comment]
@willdurand The README has been updated.

**Review by willdurand — APPROVED** [review]
That looks good to me but we should make sure the team wants to adopt this approach so I am going to request review from everyone else (we don't need a meeting I think).

As for myself: although I don't like pre-commit hooks because it slows me down, it's a good solution for contributors who aren't familiar with the project so I am :+1: on this. `husky` is quite popular in the JS world and `lint-staged` seems like a much better solution than `git status --porcelain`. I believe we should adopt both tools otherwise contributors will likely _not_ install the git hooks themselves. There is a way to ignore the hooks so that's good (there is `--no-verify` but also an env var can be used IIRC).

**Comment by bobsilverberg** [comment]
> That looks good to me but we should make sure the team wants to adopt this approach so I am going to request review from everyone else (we don't need a meeting I think).
> 

I agree. I look forward to hearing what the others think.

**Review by eviljeff — COMMENTED** [review]
So, I'm not sure who the target audience is for this fix.  Style errors would eventually get flagged in CI so they're already prevented from landing.  For internal development (i.e. _us_), I thought each person would already have their own preferred setup, be it editor plugins, or custom git hooks, (or muscle memory). If it's for contributors? This would ease that part of the process for them, I agree; but if it's _just_ for contributors it seems to me quite a heavy solution of packages that will delay every commit while the scripts are run (unless we adjust our muscle memory to regularly add `--no-verify`).

I'm unconvinced but I don't have a huge amount of skin the game here because developing for addons-frontend is the exception for me (currently, anyway) so 🤷‍♂️

**Comment by bobsilverberg** [comment]
> So, I'm not sure who the target audience is for this fix. Style errors would eventually get flagged in CI so they're already prevented from landing. For internal development (i.e. _us_), I thought each person would already have their own preferred setup, be it editor plugins, or custom git hooks, (or muscle memory). If it's for contributors? This would ease that part of the process for them, I agree; but if it's _just_ for contributors it seems to me quite a heavy solution of packages that will delay every commit while the scripts are run (unless we adjust our muscle memory to regularly add `--no-verify`).
> 
> I'm unconvinced but I don't have a huge amount of skin the game here because developing for addons-frontend is the exception for me (currently, anyway) so 🤷‍♂️

The target is mostly contributors, but I myself have found the occasional eslint error creeping into my commits, which I then don't discover until CI has failed, and I'd prefer to find them earlier than that.

As for added time, it's fairly negligible in my mind. Sure, it adds a second or two, and can be a bit longer if there have been a lot of files changed since the last commit, but I don't move so quickly that an extra second or two is going to actually slow me down.

**Comment by diox** [comment]
I don't particularly like pre-commit hooks myself, for the same reasons other cited, but I'm fine with it if we think it'll help contributors. Worse case scenario if we do find it too intrusive we can go back.

**Review by diox — APPROVED** [review]

**Pull request merged**
