### PR TITLE
Support Abuse Report hand-off in clients that support it

### LINKED ISSUE #8762: Support Abuse Report hand-off in clients that support it
Depends on https://github.com/mozilla/addons-server/issues/12741

In [bug 1580561](https://bugzilla.mozilla.org/show_bug.cgi?id=1580561), we implemented an API that allows AMO to trigger the Abuse Report flow in Firefox, for a specific add-on. We need to hook up the current Report Abuse feature to work with it. This just landed in 71.

For clients that have this new API available, clicking on on the "Report this add-on for abuse" button should call this API instead of showing the current form. All other clients should continue using the current UX.

For QA:

- On versions of Firefox below 71, nothing about the report abuse flow should change.
- On Firefox 71 and above, when clicking the "Report this add-on for abuse", the built-in Firefox dialogs will be used to report abuse. Note that this will only happen if the user also has `extensions.abuseReport.amWebAPI.enabled` set to `true`. To test this on dev, `extensions.abuseReport.amoDetailsURL` should also be set to `https://addons-dev.allizom.org/api/v4/addons/addon/` and `extensions.abuseReport.url` should be set to `https://addons-dev.allizom.org/api/v4/abuse/report/addon/`.

Note also that when using the built-in Firefox flow:
- Once the Firefox dialog is opened, the "Report this add-on for abuse" button should be disabled until the Firefox flow completes.
- If the user successfully completes the abuse report (i.e., does not click "Cancel"), the "Report this add-on for abuse" button will be replaced with a message saying "You reported this add-on for abuse", which is exactly the same as what would happen after an abuse report is submitted using the older AMO flow.

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #8762

### CODE REVIEW

**Comment by bobsilverberg** [comment]
> Will this be available in Firefox for Android? If so, how would that work?

I don't think so, but we should ask. 

@muffinresearch and/or @jvillalobos do you know if this API is expected to be available in Firefox for Android?

**Comment by muffinresearch** [comment]
> > Will this be available in Firefox for Android? If so, how would that work?
> 
> I don't think so, but we should ask.
> 
> @muffinresearch and/or @jvillalobos do you know if this API is expected to be available in Firefox for Android?

I don't know. If Jorge doesn't know either let me know and I can try and find out.

**Comment by bobsilverberg** [comment]
@rpl Do you know if this new abuse reporting API is available on Android, and/or if there are any plans to implement it in the future?

**Comment by jvillalobos** [comment]
It won't be implemented in Fennec, but I expect it to make it to Fenix eventually. Personally, I want it to be part of Fenix as early as possible, but it obviously needs to be balanced with many other product requirements for that project.

However, the expectation is that, at least at first, add-ons for Fenix will only be available via its Add-ons Manager and not through AMO. So, we wouldn't need to worry about this AMO-Firefox integration to be needed for Android anytime soon, if ever.

**Comment by bobsilverberg** [comment]
Thanks @jvillalobos. I believe that the code as written would still work on Fenix, if the API were available, so even if we don't expect that to be needed, this could should work.

I believe this is now safe to merge and land.

**Pull request merged**
