### PR TITLE
Disable CSP for development

### PR DESCRIPTION
**Pull request by kumar303**
We used to have support for `CSP: false`. We should probably just bring that back but until then, this seems worth documenting.

### CODE REVIEW

**Comment by muffinresearch** [comment]
It might be nicer to add some config and use that flag on the server to avoid the setup of the CSP middleware at all?

Better still would be adding the necessary rules to make the development server mode not cause CSP errors, but that will definitely take some doing.

**Comment by kumar303** [comment]
ok, let me try this. I think last time I tried it I was overwhelmed by the lack of unit testability of `server/base.js`

**Comment by kumar303** [comment]
actually, https://github.com/mozilla/addons-frontend/commit/66b62233e0296012b785b69412853ce36e49552f broke my config hack anyway :clown_face: What happens is that introducing a nonce for the style source [disables unsafe-inline](https://blogs.dropbox.com/tech/2015/09/unsafe-inline-and-nonce-deployment/).

**Comment by kumar303** [comment]
r? It seems to work. I can't see an easy way to write a test for this but since it's just for development I'm not worried about it breaking without us knowing about it.

**Comment by muffinresearch** [comment]
Nice, it's much cleaner like this. r+

**Pull request merged**
