### PR TITLE
Fixes #9042

### LINKED ISSUE #9042: Sort themes in chronological order from user's profile page
This request came in from our theme reviewers. 

When reviewing themes, reviewers will check if a user has submitted a duplicate theme by going to their profile page. Currently, themes listed on the profile page are sorted by # of users, which can make it hard to identify themes that have been recently submitted. 

Screen Shot 2019-12-17 at 9 26 53 AM

It would be great if themes could be sorted chronologically from a user's profile page.

### PR DESCRIPTION
**Pull request by Vishalghyv**
Fixes #9042 

Added sort options in Userprofile.js and filtered them in addons byauthors

### CODE REVIEW

**Comment by Vishalghyv** [comment]
Hi, Thanks for the Reviewing my pull request.
I had a question regarding the approach.
       Can't I use the paginated page and no of paginated result per page and then using them change       the addons. This would be make the time complexity also dependent on no of results per page.

**Comment by muffinresearch** [comment]
> Hi, Thanks for the Reviewing my pull request.
> I had a question regarding the approach.
> Can't I use the paginated page and no of paginated result per page and then using them change the addons. This would be make the time complexity also dependent on no of results per page.

Unfortunately not. As mentioned above, doing this would be sorting each page, which will not lead to the expected results and it's also not consistent with how search filters work elsewhere.

**Comment by Vishalghyv** [comment]
Okay, Surely fixing this issue would be complicated and take time thus I am closing the pull request.
Thanks for the help.

**Comment by Vishalghyv** [comment]
Okay, Surely fixing this issue is complicated and would take time thus closing this pull request.
Thanks for reviewing

**Pull request closed without merging**
