### PR TITLE
Added new line under Get Involved

### LINKED ISSUE #7838: Add info about AMO API to /about page
On https://addons.mozilla.org/about, let's add some info about the AMO API. 

Under **Get  Involved,** let's add: 

- Want to interact with addons.mozilla.org (AMO) programmatically?  Check out the documentation for the [Add-ons Servers documentation](https://addons-server.readthedocs.io/en/latest/index.html) for details about the AMO APIs, the APIs used by the [Add-ons Manager](https://blog.mozilla.org/firefox/add-ons-manager/).

Related note: can we also add a '.' next to 'wiki' at the end of To see more ways you can contribute to the add-on community, please visit our wiki?

### PR DESCRIPTION
**Pull request by rahulsyal2512**
Fixes #7838

---

Under Get Involved, Added new line :

Want to interact with addons.mozilla.org (AMO) programmatically? Check out the documentation for the Add-ons Servers documentation for details about the AMO APIs, the APIs used by the Add-ons Manager.

### CODE REVIEW

**Comment by rahulsyal2512** [comment]
@championshuttler I have made necessary changes, please review it. Thank you for your guidance :)

**Comment by rahulsyal2512** [comment]
@championshuttler I have added period ( . ) at end of Line 189

**Comment by willdurand** [comment]
@rahulsyal2512 could you please update the copy according to this comment? https://github.com/mozilla/addons-frontend/issues/7838#issuecomment-480738536 Thanks!

**Comment by rahulsyal2512** [comment]
@championshuttler Thank you soo much for guiding me :smile:

**Comment by rahulsyal2512** [comment]
@caitmuenster I just created my account on mozillians.org. Thank you so much :smile: 
https://mozillians.org/en-US/u/syal25121997/

**Comment by caitmuenster** [comment]
You're vouched! Welcome onboard, @rahulsyal2512! We look forward to seeing you around. ✨

**Pull request merged**
