### PR TITLE
Allow to publish addons-frontend-blog-utils to npm

### LINKED ISSUE #10298: Publish addons-frontend-blog-utils on npm

### PR DESCRIPTION
**Pull request by willdurand**
Fixes #10298

---

This should do the trick.

### CODE REVIEW

**Comment by willdurand** [comment]
@muffinresearch could you please add a `NPM_TOKEN` to Circle CI?

**Comment by muffinresearch** [comment]
> @muffinresearch could you please add a `NPM_TOKEN` to Circle CI?

That's done.

**Review by diox — APPROVED** [review]
Looks ok

**Comment by willdurand** [comment]
We'll see shortly I guess

**Pull request merged**
