### PR TITLE
refactor: use async-await

### LINKED ISSUE #1473: Move all promises to async / await syntax
Promises can be very hard to read, especially when we need to do specific exception handling that should not affect the rest of the promise chain. Let's consider *fully* moving to [async / await](https://ponyfoo.com/articles/understanding-javascript-async-await) instead. 

You can grep for `\.then` in `src` to get an idea of where there are still promises. You will notice a few examples where we will still need to use promises, such as a top-level call like [createClient()](https://github.com/mozilla/addons-frontend/blob/473d5c9b267fe85e9fdc68f88884f0eee8e930a3/src/amo/client.js#L10).

Contributors: I recommend beginning with a small patch where you only fix one or two instances.

### PR DESCRIPTION
**Pull request by sidvishnoi**
Fixes #1473

Converts promises to async-await.
@kumar303 Let me know if I'm going on the right path, I'll send update for rest of files.

**PS: Please "Hide whitespace changes" to make it easier to review.**

~Edit: working on failing test.~ Missed a return, and an async test was looking for throw, instead of reject.

### CODE REVIEW

**Comment by kumar303** [comment]
@sidvishnoi thanks for getting this started. Let me know if you have any questions about the failing tests.

**Comment by sidvishnoi** [comment]
Sorry for late fixes. I'm back now.
Should I send all files in this PR or split into /test and /src?

**Comment by sidvishnoi** [comment]
All files in `src/` are done - based on grepping for `then(` and `catch(`.
I'll do files in `tests/` in a separate PR, as this one already has too many changes - though whitespace changes make it seem larger than it actually is.

**Comment by kumar303** [comment]
Thanks, I'll take a look shortly.

**Comment by willdurand** [comment]
Sorry but I don't think we can continue to help you on this patch. That's a really big change (it impacts a lot of things in our app) for a rather low added value. Adopting the async/await syntax makes sense during refactoring or for new features but updating code does not sound like an interesting job for contributors (i.e. that is not fun)

**Comment by sidvishnoi** [comment]
No problem!

**Pull request closed without merging**
