### PR TITLE
Update colors on the third shelf

### LINKED ISSUE #3543: Curated collection links are very bright
See https://addons-dev.allizom.org/en-US/firefox/

The new collection links are using new photo colours. In context these links are so bright I can't really see any other content on the page because my eye is drawn to the brightness. 

Perhaps it would be possible to reduce the intensity of the colours?

add-ons_for_firefox

### PR DESCRIPTION
**Pull request by willdurand**
Fix #3543

---

Before:

After:

Previous attempts, FTR:

screen shot 2017-10-18 at 11 46 22
screen shot 2017-10-18 at 11 46 53

### CODE REVIEW

**Comment by willdurand** [comment]
> a, went to 60 instead of 70?

I'll post a screenshot.

> b, used white instead of black?

It is not black, it is `-90` for each color

**Comment by willdurand** [comment]
-60 -60 -60 -50:

screen shot 2017-10-18 at 14 16 30

**Comment by willdurand** [comment]
-70 + white:

screen shot 2017-10-18 at 14 18 58

**Comment by willdurand** [comment]
-70 + light grey (#e9ecef) used as body background color:

screen shot 2017-10-18 at 14 21 19

**Comment by tofumatt** [comment]
I think it's way better with the grey icons 🚢

**Pull request merged**
