### PR TITLE
Change default-line-height to 1.5 to fix truncation issue 

### LINKED ISSUE #10267: Display name is now aligned but the "y" and "g" look truncated
As a followup for https://github.com/mozilla/addons-frontend/issues/10260#issuecomment-805773442

Display name is now aligned but the "y" and "g" look truncated (similar with what's now in production with font of 12px)

sample one

sample2

this is at 12 px (as it is right now on AMO prod): 

before

I don't see it reproducible on Chrome (or Edge):

with Chrome1

### LINKED ISSUE #10405: Add-on reviews, letters hidden (fractionally) by rounded corners
On pages with add-on reviews that contain at least one line of text, the lower left corner of the text is sometimes hidden by the rounded corner overlapping(?) the text and cutting off certain letters' tails below the typographical font baseline, most prominently with the lower letters p and g, but other letters are affected as well (even upper letters, although this may seem petty).

210417_addons mozilla org_issue_report
210417_addons mozilla org_issue_report_1

The letter p of "preview" looks slightly confusing, almost like an o, and the letter g looks almost like a q.

### PR DESCRIPTION
**Pull request by championshuttler**
Fixes #10267
Fixes #10405

### CODE REVIEW

**Review by willdurand — CHANGES_REQUESTED** [review]
I don't think we should fix this problem only, it looks more like a problem with the global `line-height` value.

**Comment by championshuttler** [comment]
@willdurand you mean https://github.com/mozilla/addons-frontend/blob/master/src/amo/css/inc/vars.scss#L25? I think if we increase it to 1.5 it will not hurt

**Comment by willdurand** [comment]
> @willdurand you mean [`master`/src/amo/css/inc/vars.scss#L25](https://github.com/mozilla/addons-frontend/blob/master/src/amo/css/inc/vars.scss#L25)? I think if we increase it to 1.5 it will not hurt

Yes, although it might be good to keep `1.2` for headings.

**Comment by championshuttler** [comment]
> although it might be good to keep `1.2` for headings.

Sorry but where its defined, i am missing soemthing?

**Comment by willdurand** [comment]
> Sorry but where its defined, i am missing something?

I don't think we have a line height for headings (yet) because we only used `1.2` for everything until now.

**Comment by championshuttler** [comment]
I tested headings on 1.5 and they looked fine to me though

**Comment by bobsilverberg** [comment]
I suppose introducing a default line-height for headings would be part of https://github.com/mozilla/addons-frontend/issues/10251. I can probably get to that this week, after all the experiment stuff is dealt with, if you want me to take that back @willdurand. I imagine you're pretty busy with the blog?

**Comment by willdurand** [comment]
> I imagine you're pretty busy with the blog?

Yes :(

**Comment by bobsilverberg** [comment]
@championshuttler Can you please update the title of this to explain that it is about changing the default line-height. Also, I think we can add that this fixes #10405 too.

**Comment by championshuttler** [comment]
Hey @bobsilverberg done,  yeah i hope so it will solve that too

**Comment by bobsilverberg** [comment]
It's already been mentioned, but https://github.com/mozilla/addons-frontend/issues/10251 will be a follow-up to this to possibly change the default line-height for headings.

**Review by bobsilverberg — APPROVED** [review]

**Pull request merged**
